// ignore_for_file: prefer_const_constructors

import 'ai_model_config.dart';

/// 由 `scripts/sync_openrouter_model_catalog.dart` 增量生成。
///
/// 仅补充全量基线目录中缺失的当前在线模型，不删除历史型号。
final Map<String, AiModelProfile>
openRouterLatestModelProfiles = <String, AiModelProfile>{
  "aion-labs/aion-3.0": AiModelProfile(
    displayName: "Aion-3.0",
    description:
        "Aion-3.0 is a multi-model roleplaying and storytelling system from AionLabs, built on the GLM family of models. It uses a collaborative generation process in which multiple specialized models each contribute...",
    supportedModalities: <AiModelModality>{AiModelModality.text},
    maxContextLength: 131072,
    maxOutputLength: 32768,
    maxThinkingLength: 32768,
    thinkingEnabled: true,
    inputUsdPer1M: 3,
    outputUsdPer1M: 6,
    cacheReadUsdPer1M: 0.75,
    canonicalSlug: "aion-labs/aion-3.0-20260707",
    created: 1783443095,
    architecture: AiModelArchitectureMetadata(
      modality: "text->text",
      inputModalities: <String>["text"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "response_format",
      "temperature",
      "tool_choice",
      "tools",
      "top_p",
    ],
    links: AiModelLinksMetadata(
      details: "/api/v1/models/aion-labs/aion-3.0-20260707/endpoints",
    ),
  ),
  "aion-labs/aion-3.0-mini": AiModelProfile(
    displayName: "Aion-3.0-Mini",
    description:
        "Aion-3.0 Mini is a multi-model roleplaying and storytelling system from AionLabs, built on the DeepSeek family of models. It uses a collaborative generation process in which multiple specialized models each...",
    supportedModalities: <AiModelModality>{AiModelModality.text},
    maxContextLength: 131072,
    maxOutputLength: 32768,
    maxThinkingLength: 32768,
    thinkingEnabled: true,
    inputUsdPer1M: 0.7,
    outputUsdPer1M: 1.4,
    cacheReadUsdPer1M: 0.18,
    canonicalSlug: "aion-labs/aion-3.0-mini-20260707",
    created: 1783443096,
    architecture: AiModelArchitectureMetadata(
      modality: "text->text",
      inputModalities: <String>["text"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "response_format",
      "temperature",
      "tool_choice",
      "tools",
      "top_p",
    ],
    links: AiModelLinksMetadata(
      details: "/api/v1/models/aion-labs/aion-3.0-mini-20260707/endpoints",
    ),
  ),
  "anthropic/claude-fable-5": AiModelProfile(
    displayName: "Claude Fable 5",
    description:
        "Claude Fable 5 is a Mythos-class model from Anthropic, built for autonomous knowledge work and coding. It supports text, image, and file inputs with text output, with reasoning support and...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.file,
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 1000000,
    maxOutputLength: 128000,
    maxThinkingLength: 128000,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "high",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["max", "xhigh", "high", "medium", "low"],
    ),
    inputUsdPer1M: 10,
    outputUsdPer1M: 50,
    cacheReadUsdPer1M: 1,
    cacheWriteUsdPer1M: 12.5,
    canonicalSlug: "anthropic/claude-5-fable-20260609",
    created: 1781007515,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+file->text",
      inputModalities: <String>["text", "image", "file"],
      outputModalities: <String>["text"],
      tokenizer: "Claude",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_completion_tokens",
      "max_tokens",
      "reasoning",
      "reasoning_effort",
      "response_format",
      "stop",
      "structured_outputs",
      "tool_choice",
      "tools",
      "verbosity",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/anthropic/claude-5-fable-20260609/endpoints",
    ),
  ),
  "anthropic/claude-opus-5": AiModelProfile(
    displayName: "Claude Opus 5",
    description:
        "Claude Opus 5 is Anthropic’s flagship model for demanding reasoning, coding, and long-horizon agentic work. It is particularly strong at end-to-end software tasks, code review and bug finding, visual analysis...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.file,
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 1000000,
    maxOutputLength: 128000,
    maxThinkingLength: 128000,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "high",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["max", "xhigh", "high", "medium", "low"],
    ),
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
    canonicalSlug: "anthropic/claude-opus-5-20260723",
    created: 1784912544,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+file->text",
      inputModalities: <String>["text", "image", "file"],
      outputModalities: <String>["text"],
      tokenizer: "Claude",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_completion_tokens",
      "max_tokens",
      "reasoning",
      "reasoning_effort",
      "response_format",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "verbosity",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/anthropic/claude-opus-5-20260723/endpoints",
    ),
  ),
  "anthropic/claude-opus-5-fast": AiModelProfile(
    displayName: "Claude Opus 5 (Fast)",
    description:
        "Fast-mode variant of [Opus 5](/anthropic/claude-opus-5) - identical capabilities with higher output speed at 2x pricing relative to regular Opus 5.\n\nLearn more in Anthropic's docs: https://platform.claude.com/docs/en/build-with-claude/fast-mode",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.file,
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 1000000,
    maxOutputLength: 128000,
    maxThinkingLength: 128000,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "high",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["max", "xhigh", "high", "medium", "low"],
    ),
    inputUsdPer1M: 10,
    outputUsdPer1M: 50,
    cacheReadUsdPer1M: 1,
    cacheWriteUsdPer1M: 12.5,
    canonicalSlug: "anthropic/claude-opus-5-fast-20260723",
    created: 1784912546,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+file->text",
      inputModalities: <String>["text", "image", "file"],
      outputModalities: <String>["text"],
      tokenizer: "Claude",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "reasoning_effort",
      "response_format",
      "stop",
      "structured_outputs",
      "tool_choice",
      "tools",
      "verbosity",
    ],
    links: AiModelLinksMetadata(
      details: "/api/v1/models/anthropic/claude-opus-5-fast-20260723/endpoints",
    ),
  ),
  "anthropic/claude-sonnet-5": AiModelProfile(
    displayName: "Claude Sonnet 5",
    description:
        "Sonnet 5 is Anthropic's most capable Sonnet-class model, with frontier performance across coding, agents, and professional work. It supports adaptive thinking with selectable reasoning effort levels (low, medium, high, max,...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.file,
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 1000000,
    maxOutputLength: 128000,
    maxThinkingLength: 128000,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "high",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["max", "xhigh", "high", "medium", "low"],
    ),
    inputUsdPer1M: 2,
    outputUsdPer1M: 10,
    cacheReadUsdPer1M: 0.2,
    cacheWriteUsdPer1M: 2.5,
    canonicalSlug: "anthropic/claude-sonnet-5-20260630",
    created: 1782843083,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+file->text",
      inputModalities: <String>["text", "image", "file"],
      outputModalities: <String>["text"],
      tokenizer: "Claude",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_completion_tokens",
      "max_tokens",
      "reasoning",
      "reasoning_effort",
      "response_format",
      "stop",
      "structured_outputs",
      "tool_choice",
      "tools",
      "verbosity",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/anthropic/claude-sonnet-5-20260630/endpoints",
    ),
  ),
  "cognitivecomputations/dolphin-mistral-24b-venice-edition": AiModelProfile(
    displayName: "Uncensored",
    description:
        "Venice Uncensored Dolphin Mistral 24B Venice Edition is a fine-tuned variant of Mistral-Small-24B-Instruct-2501, developed by dphn.ai in collaboration with Venice.ai. This model is designed as an “uncensored” instruct-tuned LLM, preserving...",
    supportedModalities: <AiModelModality>{AiModelModality.text},
    maxContextLength: 128000,
    maxOutputLength: 8192,
    inputUsdPer1M: 0.2,
    outputUsdPer1M: 0.9,
    canonicalSlug: "venice/uncensored",
    huggingFaceId: "cognitivecomputations/Dolphin-Mistral-24B-Venice-Edition",
    created: 1752094966,
    architecture: AiModelArchitectureMetadata(
      modality: "text->text",
      inputModalities: <String>["text"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "max_tokens",
      "presence_penalty",
      "response_format",
      "stop",
      "temperature",
      "top_k",
      "top_p",
    ],
    knowledgeCutoff: "2024-04-30",
    links: AiModelLinksMetadata(
      details: "/api/v1/models/venice/uncensored/endpoints",
    ),
  ),
  "cohere/north-mini-code:free": AiModelProfile(
    displayName: "North Mini Code (free)",
    description:
        "North Mini Code is Cohere's first agentic coding model and the debut of its North family. A sparse mixture-of-experts model with 30B total parameters and 3B active, it is optimized...",
    supportedModalities: <AiModelModality>{AiModelModality.text},
    maxContextLength: 256000,
    maxOutputLength: 64000,
    maxThinkingLength: 64000,
    inputUsdPer1M: 0,
    outputUsdPer1M: 0,
    canonicalSlug: "cohere/north-mini-code-20260617",
    huggingFaceId: "CohereLabs/North-Mini-Code-1.0",
    created: 1781723748,
    architecture: AiModelArchitectureMetadata(
      modality: "text->text",
      inputModalities: <String>["text"],
      outputModalities: <String>["text"],
      tokenizer: "Cohere",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "include_reasoning",
      "max_tokens",
      "presence_penalty",
      "reasoning",
      "seed",
      "stop",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/cohere/north-mini-code-20260617/endpoints",
    ),
  ),
  "deepseek/deepseek-v4-flash-0731": AiModelProfile(
    displayName: "DeepSeek V4 Flash 0731",
    description:
        "DeepSeek V4 Flash 0731 is a sparse mixture-of-experts model from DeepSeek, with 13B active parameters out of 284B total. This re-post-trained revision is suited for coding, reasoning, and agent workflows.",
    supportedModalities: <AiModelModality>{AiModelModality.text},
    maxContextLength: 1048576,
    maxOutputLength: 65536,
    maxThinkingLength: 65536,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "high",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["max", "high", "low"],
    ),
    inputUsdPer1M: 0.09,
    outputUsdPer1M: 0.18,
    cacheReadUsdPer1M: 0.018,
    canonicalSlug: "deepseek/deepseek-v4-flash-20260731",
    huggingFaceId: "deepseek-ai/DeepSeek-V4-Flash-0731",
    created: 1785478908,
    architecture: AiModelArchitectureMetadata(
      modality: "text->text",
      inputModalities: <String>["text"],
      outputModalities: <String>["text"],
      tokenizer: "DeepSeek",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "include_reasoning",
      "logit_bias",
      "logprobs",
      "max_tokens",
      "min_p",
      "presence_penalty",
      "reasoning",
      "reasoning_effort",
      "repetition_penalty",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_a",
      "top_k",
      "top_logprobs",
      "top_p",
    ],
    links: AiModelLinksMetadata(
      details: "/api/v1/models/deepseek/deepseek-v4-flash-20260731/endpoints",
    ),
  ),
  "google/gemini-3-pro-image": AiModelProfile(
    displayName: "Nano Banana Pro (Gemini 3 Pro Image)",
    description:
        "Nano Banana Pro is Google’s most advanced image-generation and editing model, built on Gemini 3 Pro. It extends the original Nano Banana with significantly improved multimodal reasoning, real-world grounding, and...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 131072,
    maxOutputLength: 32768,
    maxThinkingLength: 32768,
    thinkingEnabled: true,
    capabilities: <AiModelCapability>{AiModelCapability.imageGeneration},
    inputUsdPer1M: 2,
    outputUsdPer1M: 12,
    cacheReadUsdPer1M: 0.2,
    cacheWriteUsdPer1M: 0.375,
    canonicalSlug: "google/gemini-3-pro-image-20260528",
    created: 1781754054,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image->text+image",
      inputModalities: <String>["image", "text"],
      outputModalities: <String>["image", "text"],
      tokenizer: "Gemini",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_p",
    ],
    links: AiModelLinksMetadata(
      details: "/api/v1/models/google/gemini-3-pro-image-20260528/endpoints",
    ),
  ),
  "google/gemini-3.1-flash-image": AiModelProfile(
    displayName: "Nano Banana 2 (Gemini 3.1 Flash Image)",
    description:
        "Gemini 3.1 Flash Image, a.k.a. \"Nano Banana 2,\" is Google’s latest state of the art image generation and editing model, delivering Pro-level visual quality at Flash speed. It combines advanced...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 131072,
    maxOutputLength: 32768,
    maxThinkingLength: 32768,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "minimal",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["high", "minimal"],
    ),
    capabilities: <AiModelCapability>{AiModelCapability.imageGeneration},
    inputUsdPer1M: 0.5,
    outputUsdPer1M: 3,
    canonicalSlug: "google/gemini-3.1-flash-image-20260528",
    created: 1781754065,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image->text+image",
      inputModalities: <String>["image", "text"],
      outputModalities: <String>["image", "text"],
      tokenizer: "Gemini",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "reasoning_effort",
      "response_format",
      "seed",
      "structured_outputs",
      "temperature",
      "top_p",
    ],
    links: AiModelLinksMetadata(
      details:
          "/api/v1/models/google/gemini-3.1-flash-image-20260528/endpoints",
    ),
  ),
  "google/gemini-3.1-flash-lite-image": AiModelProfile(
    displayName: "Nano Banana 2 Lite (Gemini 3.1 Flash Lite Image)",
    description:
        "Nano Banana 2 Lite (Gemini 3.1 Flash Lite Image) is Google's fastest, most cost-efficient Gemini image model, built for high-velocity developer pipelines and rapid-fire visual exploration. It delivers text-to-image generation...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 65536,
    maxOutputLength: 65536,
    maxThinkingLength: 65536,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "minimal",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["high", "minimal"],
    ),
    capabilities: <AiModelCapability>{AiModelCapability.imageGeneration},
    inputUsdPer1M: 0.25,
    outputUsdPer1M: 1.5,
    canonicalSlug: "google/gemini-3.1-flash-lite-image-20260630",
    created: 1782837225,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image->text+image",
      inputModalities: <String>["image", "text"],
      outputModalities: <String>["image", "text"],
      tokenizer: "Gemini",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "reasoning_effort",
      "response_format",
      "seed",
      "temperature",
      "top_p",
    ],
    knowledgeCutoff: "2025-01-01",
    links: AiModelLinksMetadata(
      details:
          "/api/v1/models/google/gemini-3.1-flash-lite-image-20260630/endpoints",
    ),
  ),
  "google/gemini-3.5-flash-lite": AiModelProfile(
    displayName: "Gemini 3.5 Flash Lite",
    description:
        "Gemini 3.5 Flash Lite is a high-efficiency model from Google with upgraded agentic capabilities. It is suited for subagents that execute focused tasks within complex, multi-agent workflows.",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.audio,
      AiModelModality.file,
      AiModelModality.image,
      AiModelModality.text,
      AiModelModality.video,
    },
    maxContextLength: 1048576,
    maxOutputLength: 65536,
    maxThinkingLength: 65536,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "minimal",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["high", "medium", "low", "minimal"],
    ),
    inputUsdPer1M: 0.3,
    outputUsdPer1M: 2.5,
    cacheReadUsdPer1M: 0.03,
    cacheWriteUsdPer1M: 0.0833333333,
    canonicalSlug: "google/gemini-3.5-flash-lite-20260721",
    created: 1784646726,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+file+audio+video->text",
      inputModalities: <String>["text", "image", "video", "file", "audio"],
      outputModalities: <String>["text"],
      tokenizer: "Gemini",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "reasoning_effort",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/google/gemini-3.5-flash-lite-20260721/endpoints",
    ),
  ),
  "google/gemini-3.6-flash": AiModelProfile(
    displayName: "Gemini 3.6 Flash",
    description:
        "Gemini 3.6 Flash is a high-efficiency model from Google for coding, agentic workflows, and web and app development. It is designed to produce polished outputs with fewer unnecessary edits and...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.audio,
      AiModelModality.file,
      AiModelModality.image,
      AiModelModality.text,
      AiModelModality.video,
    },
    maxContextLength: 1048576,
    maxOutputLength: 65536,
    maxThinkingLength: 65536,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "medium",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["high", "medium", "low", "minimal"],
    ),
    inputUsdPer1M: 1.5,
    outputUsdPer1M: 7.5,
    cacheReadUsdPer1M: 0.15,
    cacheWriteUsdPer1M: 0.0833333333,
    canonicalSlug: "google/gemini-3.6-flash-20260721",
    created: 1784646733,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+file+audio+video->text",
      inputModalities: <String>["text", "image", "video", "file", "audio"],
      outputModalities: <String>["text"],
      tokenizer: "Gemini",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "reasoning_effort",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/google/gemini-3.6-flash-20260721/endpoints",
    ),
  ),
  "inclusionai/ling-3.0-flash:free": AiModelProfile(
    displayName: "Ling-3.0-flash (free)",
    description:
        "*Ling-3.0-flash* is a *124B-parameter Mixture-of-Experts (MoE) model*, with approximately *5.1B parameters activated per token*. The model is designed with *token efficiency and production-scale agentic inference* as key priorities, enabling developers...",
    supportedModalities: <AiModelModality>{AiModelModality.text},
    maxContextLength: 262144,
    maxOutputLength: 32768,
    maxThinkingLength: 32768,
    thinkingEnabled: true,
    inputUsdPer1M: 0,
    outputUsdPer1M: 0,
    canonicalSlug: "inclusionai/ling-3.0-flash-20260723",
    created: 1784818580,
    architecture: AiModelArchitectureMetadata(
      modality: "text->text",
      inputModalities: <String>["text"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "include_reasoning",
      "logprobs",
      "max_tokens",
      "presence_penalty",
      "reasoning",
      "repetition_penalty",
      "seed",
      "stop",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_logprobs",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/inclusionai/ling-3.0-flash-20260723/endpoints",
    ),
  ),
  "kwaipilot/kat-coder-air-v2.5": AiModelProfile(
    displayName: "KAT-Coder-Air V2.5",
    description:
        "KAT-Coder-Air V2.5 is a flagship-level Agentic Coding model that can directly hand over an entire issue or an entire business workflow to it, allowing it to autonomously locate and make...",
    supportedModalities: <AiModelModality>{AiModelModality.text},
    maxContextLength: 256000,
    maxOutputLength: 80000,
    inputUsdPer1M: 0.15,
    outputUsdPer1M: 0.6,
    cacheReadUsdPer1M: 0.03,
    canonicalSlug: "kwaipilot/kat-coder-air-v2.5-20260710",
    created: 1783714590,
    architecture: AiModelArchitectureMetadata(
      modality: "text->text",
      inputModalities: <String>["text"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "logprobs",
      "max_tokens",
      "presence_penalty",
      "response_format",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_logprobs",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/kwaipilot/kat-coder-air-v2.5-20260710/endpoints",
    ),
  ),
  "kwaipilot/kat-coder-pro-v2.5": AiModelProfile(
    displayName: "KAT-Coder-Pro V2.5",
    description:
        "KAT-Coder-Pro V2.5 is a flagship-level Agentic Coding model that can directly hand over an entire issue or an entire business workflow to it, allowing it to autonomously locate and make...",
    supportedModalities: <AiModelModality>{AiModelModality.text},
    maxContextLength: 256000,
    maxOutputLength: 80000,
    inputUsdPer1M: 0.74,
    outputUsdPer1M: 2.96,
    cacheReadUsdPer1M: 0.15,
    canonicalSlug: "kwaipilot/kat-coder-pro-v2.5-20260710",
    created: 1783714589,
    architecture: AiModelArchitectureMetadata(
      modality: "text->text",
      inputModalities: <String>["text"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "logprobs",
      "max_tokens",
      "presence_penalty",
      "response_format",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_logprobs",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/kwaipilot/kat-coder-pro-v2.5-20260710/endpoints",
    ),
  ),
  "meituan/longcat-2.0": AiModelProfile(
    displayName: "LongCat 2.0",
    description:
        "LongCat 2.0 is a sparse mixture-of-experts language model from Meituan, with 48B active parameters out of 1.6T total. It is suited for coding, repository-level changes, long-horizon problem solving, and agentic...",
    supportedModalities: <AiModelModality>{AiModelModality.text},
    maxContextLength: 1048756,
    maxOutputLength: 262144,
    maxThinkingLength: 262144,
    thinkingEnabled: true,
    inputUsdPer1M: 0.3,
    outputUsdPer1M: 1.2,
    cacheReadUsdPer1M: 0.006,
    canonicalSlug: "meituan/longcat-2.0-20260720",
    huggingFaceId: "meituan-longcat/LongCat-2.0",
    created: 1784554658,
    architecture: AiModelArchitectureMetadata(
      modality: "text->text",
      inputModalities: <String>["text"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "include_reasoning",
      "logit_bias",
      "max_tokens",
      "min_p",
      "presence_penalty",
      "reasoning",
      "repetition_penalty",
      "seed",
      "stop",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_p",
    ],
    links: AiModelLinksMetadata(
      details: "/api/v1/models/meituan/longcat-2.0-20260720/endpoints",
    ),
  ),
  "meta/muse-spark-1.1": AiModelProfile(
    displayName: "Muse Spark 1.1",
    description:
        "Muse Spark 1.1 is a multimodal reasoning model from Meta, built for agentic tasks. It accepts text, images, video, audio, and PDF documents and returns text, with a 1M-token context...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.audio,
      AiModelModality.file,
      AiModelModality.image,
      AiModelModality.text,
      AiModelModality.video,
    },
    maxContextLength: 1048576,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "medium",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["xhigh", "high", "medium", "low", "minimal"],
    ),
    inputUsdPer1M: 1.25,
    outputUsdPer1M: 4.25,
    cacheReadUsdPer1M: 0.15,
    canonicalSlug: "meta/muse-spark-1.1-20260709",
    created: 1784215741,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+file+audio+video->text",
      inputModalities: <String>["text", "image", "video", "file", "audio"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "reasoning_effort",
      "repetition_penalty",
      "response_format",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/meta/muse-spark-1.1-20260709/endpoints",
    ),
  ),
  "minimax/minimax-m3": AiModelProfile(
    displayName: "MiniMax M3",
    description:
        "MiniMax-M3 is a multimodal foundation model from MiniMax. It supports text, image, and video inputs with text output, a 1M-token context window, and is suited for long-horizon agentic work, coding,...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.image,
      AiModelModality.text,
      AiModelModality.video,
    },
    maxContextLength: 1048576,
    maxOutputLength: 512000,
    maxThinkingLength: 512000,
    inputUsdPer1M: 0.3,
    outputUsdPer1M: 1.2,
    cacheReadUsdPer1M: 0.06,
    canonicalSlug: "minimax/minimax-m3-20260531",
    huggingFaceId: "MiniMaxAI/Minimax-M3",
    created: 1780245374,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+video->text",
      inputModalities: <String>["text", "image", "video"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "include_reasoning",
      "logit_bias",
      "logprobs",
      "max_tokens",
      "min_p",
      "presence_penalty",
      "reasoning",
      "repetition_penalty",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_logprobs",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": 1,
      "top_p": 0.95,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/minimax/minimax-m3-20260531/endpoints",
    ),
  ),
  "moonshotai/kimi-k2.7-code": AiModelProfile(
    displayName: "Kimi K2.7 Code",
    description:
        "MoonshotAI: Kimi K2.7 Code is a coding-focused model in Moonshot AI's Kimi K2 family, built to complete end-to-end programming tasks reliably over long contexts. It uses a native multimodal mixture-of-experts...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 262144,
    maxOutputLength: 262144,
    maxThinkingLength: 262144,
    thinkingEnabled: true,
    inputUsdPer1M: 0.73,
    outputUsdPer1M: 3.5,
    cacheReadUsdPer1M: 0.15,
    canonicalSlug: "moonshotai/kimi-k2.7-code-20260612",
    huggingFaceId: "moonshotai/Kimi-K2.7-Code",
    created: 1781266361,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image->text",
      inputModalities: <String>["text", "image"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "include_reasoning",
      "logit_bias",
      "logprobs",
      "max_tokens",
      "min_p",
      "parallel_tool_calls",
      "presence_penalty",
      "reasoning",
      "repetition_penalty",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_logprobs",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/moonshotai/kimi-k2.7-code-20260612/endpoints",
    ),
  ),
  "moonshotai/kimi-k3": AiModelProfile(
    displayName: "Kimi K3",
    description:
        "Kimi K3 is a 2.8T parameter open-weight multimodal reasoning model from Moonshot AI. It is suited for complex coding, knowledge work, and long-horizon agentic workflows, and is particularly strong at...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 1048576,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "max",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["max", "high", "low"],
    ),
    inputUsdPer1M: 3,
    outputUsdPer1M: 15,
    cacheReadUsdPer1M: 0.3,
    canonicalSlug: "moonshotai/kimi-k3-20260715",
    huggingFaceId: "moonshotai/Kimi-K3",
    created: 1784215858,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image->text",
      inputModalities: <String>["text", "image"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "include_reasoning",
      "logit_bias",
      "logprobs",
      "max_tokens",
      "min_p",
      "presence_penalty",
      "reasoning",
      "reasoning_effort",
      "repetition_penalty",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_logprobs",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": 0.95,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/moonshotai/kimi-k3-20260715/endpoints",
    ),
  ),
  "nex-agi/nex-n2-mini": AiModelProfile(
    displayName: "Nex-N2-Mini",
    description:
        "Nex-N2-Mini is an open-source agentic mixture-of-experts model from Nex AGI, the smaller sibling in the Nex-N2 series. It accepts text and image input and is built for coding, tool use,...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 262144,
    maxOutputLength: 262144,
    maxThinkingLength: 262144,
    inputUsdPer1M: 0.025,
    outputUsdPer1M: 0.1,
    cacheReadUsdPer1M: 0.0025,
    canonicalSlug: "nex-agi/nex-n2-mini",
    huggingFaceId: "nex-agi/Nex-N2-Mini",
    created: 1782312964,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image->text",
      inputModalities: <String>["text", "image"],
      outputModalities: <String>["text"],
      tokenizer: "Qwen3",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "logprobs",
      "max_tokens",
      "reasoning",
      "response_format",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_logprobs",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": 0.7,
      "top_p": 0.95,
      "top_k": 40,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/nex-agi/nex-n2-mini/endpoints",
    ),
  ),
  "nex-agi/nex-n2-pro": AiModelProfile(
    displayName: "Nex-N2-Pro",
    description:
        "Nex-N2-Pro is an agentic mixture-of-experts model from Nex AGI, with 17B active parameters out of 397B total. Built on the Qwen3.5 architecture, it accepts text and image input and produces...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 262144,
    maxOutputLength: 262144,
    maxThinkingLength: 262144,
    inputUsdPer1M: 0.25,
    outputUsdPer1M: 1,
    cacheReadUsdPer1M: 0.025,
    canonicalSlug: "nex-agi/nex-n2-pro",
    huggingFaceId: "nex-agi/Nex-N2-Pro",
    created: 1780937140,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image->text",
      inputModalities: <String>["text", "image"],
      outputModalities: <String>["text"],
      tokenizer: "Qwen3",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "include_reasoning",
      "logprobs",
      "max_tokens",
      "reasoning",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_logprobs",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": 0.7,
      "top_p": 0.95,
      "top_k": 40,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/nex-agi/nex-n2-pro/endpoints",
    ),
  ),
  "nvidia/nemotron-3-ultra-550b-a55b": AiModelProfile(
    displayName: "Nemotron 3 Ultra",
    description:
        "NVIDIA Nemotron 3 Ultra is an open frontier-reasoning and orchestration model from NVIDIA, with 55B active parameters out of 550B total (MoE). Built on a hybrid Transformer-Mamba mixture-of-experts architecture, it...",
    supportedModalities: <AiModelModality>{AiModelModality.text},
    maxContextLength: 512288,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "high",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["high", "medium"],
    ),
    inputUsdPer1M: 0.6,
    outputUsdPer1M: 3.6,
    cacheReadUsdPer1M: 0.2,
    canonicalSlug: "nvidia/nemotron-3-ultra-550b-a55b-20260604",
    huggingFaceId: "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16",
    created: 1780551208,
    architecture: AiModelArchitectureMetadata(
      modality: "text->text",
      inputModalities: <String>["text"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "include_reasoning",
      "logit_bias",
      "max_tokens",
      "min_p",
      "presence_penalty",
      "reasoning",
      "reasoning_effort",
      "repetition_penalty",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": 1,
      "top_p": 0.95,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details:
          "/api/v1/models/nvidia/nemotron-3-ultra-550b-a55b-20260604/endpoints",
    ),
  ),
  "nvidia/nemotron-3-ultra-550b-a55b:free": AiModelProfile(
    displayName: "Nemotron 3 Ultra (free)",
    description:
        "NVIDIA Nemotron 3 Ultra is an open frontier-reasoning and orchestration model from NVIDIA, with 55B active parameters out of 550B total (MoE). Built on a hybrid Transformer-Mamba mixture-of-experts architecture, it...",
    supportedModalities: <AiModelModality>{AiModelModality.text},
    maxContextLength: 1000000,
    maxOutputLength: 65536,
    maxThinkingLength: 65536,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "high",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["high", "medium"],
    ),
    inputUsdPer1M: 0,
    outputUsdPer1M: 0,
    canonicalSlug: "nvidia/nemotron-3-ultra-550b-a55b-20260604",
    huggingFaceId: "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16",
    created: 1780551208,
    architecture: AiModelArchitectureMetadata(
      modality: "text->text",
      inputModalities: <String>["text"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "reasoning_effort",
      "seed",
      "temperature",
      "tool_choice",
      "tools",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": 1,
      "top_p": 0.95,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details:
          "/api/v1/models/nvidia/nemotron-3-ultra-550b-a55b-20260604/endpoints",
    ),
  ),
  "nvidia/nemotron-3.5-content-safety:free": AiModelProfile(
    displayName: "Nemotron 3.5 Content Safety (free)",
    description:
        "NVIDIA Nemotron 3.5 Content Safety is a compact 4B-parameter multimodal guardrail model from NVIDIA, fine-tuned from Google Gemma-3-4B. It moderates both inputs to and responses from LLMs and VLMs, accepting...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 128000,
    maxOutputLength: 8192,
    maxThinkingLength: 8192,
    thinkingEnabled: true,
    inputUsdPer1M: 0,
    outputUsdPer1M: 0,
    canonicalSlug: "nvidia/nemotron-3.5-content-safety-20260604",
    huggingFaceId: "nvidia/Nemotron-3.5-Content-Safety",
    created: 1780581864,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image->text",
      inputModalities: <String>["text", "image"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "seed",
      "temperature",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details:
          "/api/v1/models/nvidia/nemotron-3.5-content-safety-20260604/endpoints",
    ),
  ),
  "openai/gpt-5.6-luna": AiModelProfile(
    displayName: "GPT-5.6 Luna",
    description:
        "GPT-5.6 Luna is a fast, cost-efficient model in OpenAI's GPT-5.6 series. It is suited for high-volume, latency-sensitive tasks such as chat, classification, and lightweight agentic workflows, providing capable reasoning for...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.file,
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 1050000,
    maxOutputLength: 128000,
    maxThinkingLength: 128000,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "medium",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["max", "xhigh", "high", "medium", "low", "none"],
    ),
    inputUsdPer1M: 0.1,
    outputUsdPer1M: 0.6,
    cacheReadUsdPer1M: 0.01,
    cacheWriteUsdPer1M: 0.125,
    canonicalSlug: "openai/gpt-5.6-luna-20260709",
    created: 1783590864,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+file->text",
      inputModalities: <String>["file", "image", "text"],
      outputModalities: <String>["text"],
      tokenizer: "GPT",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_completion_tokens",
      "max_tokens",
      "reasoning",
      "reasoning_effort",
      "response_format",
      "seed",
      "structured_outputs",
      "tool_choice",
      "tools",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    knowledgeCutoff: "2026-02-16",
    links: AiModelLinksMetadata(
      details: "/api/v1/models/openai/gpt-5.6-luna-20260709/endpoints",
    ),
  ),
  "openai/gpt-5.6-luna-pro": AiModelProfile(
    displayName: "GPT-5.6 Luna Pro",
    description:
        "GPT-5.6 Luna Pro is the same underlying model as [GPT-5.6 Luna](https://openrouter.ai/openai/gpt-5.6-luna), served with `reasoning.mode` set to `pro` for higher-quality responses on complex tasks.\n\nLearn more in OpenAI's docs: https://developers.openai.com/api/docs/guides/reasoning#reasoning-mode",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.file,
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 1050000,
    maxOutputLength: 128000,
    maxThinkingLength: 128000,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "medium",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["max", "xhigh", "high", "medium", "low", "none"],
    ),
    inputUsdPer1M: 0.1,
    outputUsdPer1M: 0.6,
    cacheReadUsdPer1M: 0.01,
    cacheWriteUsdPer1M: 0.125,
    canonicalSlug: "openai/gpt-5.6-luna-pro-20260709",
    created: 1783590867,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+file->text",
      inputModalities: <String>["file", "image", "text"],
      outputModalities: <String>["text"],
      tokenizer: "GPT",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_completion_tokens",
      "max_tokens",
      "reasoning",
      "reasoning_effort",
      "response_format",
      "seed",
      "structured_outputs",
      "tool_choice",
      "tools",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    knowledgeCutoff: "2026-02-16",
    links: AiModelLinksMetadata(
      details: "/api/v1/models/openai/gpt-5.6-luna-pro-20260709/endpoints",
    ),
  ),
  "openai/gpt-5.6-sol": AiModelProfile(
    displayName: "GPT-5.6 Sol",
    description:
        "GPT-5.6 Sol is the flagship model in OpenAI's GPT-5.6 series. It is suited for complex reasoning, coding, and agentic workflows, and is particularly strong at command-line and multi-step coding tasks...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.file,
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 1050000,
    maxOutputLength: 128000,
    maxThinkingLength: 128000,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "medium",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["max", "xhigh", "high", "medium", "low", "none"],
    ),
    inputUsdPer1M: 5,
    outputUsdPer1M: 30,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
    canonicalSlug: "openai/gpt-5.6-sol-20260709",
    created: 1783590850,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+file->text",
      inputModalities: <String>["file", "image", "text"],
      outputModalities: <String>["text"],
      tokenizer: "GPT",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_completion_tokens",
      "max_tokens",
      "reasoning",
      "reasoning_effort",
      "response_format",
      "seed",
      "structured_outputs",
      "tool_choice",
      "tools",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    knowledgeCutoff: "2026-02-16",
    links: AiModelLinksMetadata(
      details: "/api/v1/models/openai/gpt-5.6-sol-20260709/endpoints",
    ),
  ),
  "openai/gpt-5.6-sol-pro": AiModelProfile(
    displayName: "GPT-5.6 Sol Pro",
    description:
        "GPT-5.6 Sol Pro is the same underlying model as [GPT-5.6 Sol](https://openrouter.ai/openai/gpt-5.6-sol), served with `reasoning.mode` set to `pro` for higher-quality responses on complex tasks.\n\nLearn more in OpenAI's docs: https://developers.openai.com/api/docs/guides/reasoning#reasoning-mode",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.file,
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 1050000,
    maxOutputLength: 128000,
    maxThinkingLength: 128000,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "medium",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["max", "xhigh", "high", "medium", "low", "none"],
    ),
    inputUsdPer1M: 5,
    outputUsdPer1M: 30,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
    canonicalSlug: "openai/gpt-5.6-sol-pro-20260709",
    created: 1783590854,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+file->text",
      inputModalities: <String>["file", "image", "text"],
      outputModalities: <String>["text"],
      tokenizer: "GPT",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_completion_tokens",
      "max_tokens",
      "reasoning",
      "reasoning_effort",
      "response_format",
      "seed",
      "structured_outputs",
      "tool_choice",
      "tools",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    knowledgeCutoff: "2026-02-16",
    links: AiModelLinksMetadata(
      details: "/api/v1/models/openai/gpt-5.6-sol-pro-20260709/endpoints",
    ),
  ),
  "openai/gpt-5.6-terra": AiModelProfile(
    displayName: "GPT-5.6 Terra",
    description:
        "GPT-5.6 Terra is a balanced model in OpenAI's GPT-5.6 series, positioned between the flagship Sol tier and the cost-efficient Luna tier. It is suited for everyday coding, reasoning, and agentic...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.file,
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 1050000,
    maxOutputLength: 128000,
    maxThinkingLength: 128000,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "medium",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["max", "xhigh", "high", "medium", "low", "none"],
    ),
    inputUsdPer1M: 1,
    outputUsdPer1M: 6,
    cacheReadUsdPer1M: 0.1,
    cacheWriteUsdPer1M: 1.25,
    canonicalSlug: "openai/gpt-5.6-terra-20260709",
    created: 1783590857,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+file->text",
      inputModalities: <String>["file", "image", "text"],
      outputModalities: <String>["text"],
      tokenizer: "GPT",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_completion_tokens",
      "max_tokens",
      "reasoning",
      "reasoning_effort",
      "response_format",
      "seed",
      "structured_outputs",
      "tool_choice",
      "tools",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    knowledgeCutoff: "2026-02-16",
    links: AiModelLinksMetadata(
      details: "/api/v1/models/openai/gpt-5.6-terra-20260709/endpoints",
    ),
  ),
  "openai/gpt-5.6-terra-pro": AiModelProfile(
    displayName: "GPT-5.6 Terra Pro",
    description:
        "GPT-5.6 Terra Pro is the same underlying model as [GPT-5.6 Terra](https://openrouter.ai/openai/gpt-5.6-terra), served with `reasoning.mode` set to `pro` for higher-quality responses on complex tasks.\n\nLearn more in OpenAI's docs: https://developers.openai.com/api/docs/guides/reasoning#reasoning-mode",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.file,
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 1050000,
    maxOutputLength: 128000,
    maxThinkingLength: 128000,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "medium",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["max", "xhigh", "high", "medium", "low", "none"],
    ),
    inputUsdPer1M: 1,
    outputUsdPer1M: 6,
    cacheReadUsdPer1M: 0.1,
    cacheWriteUsdPer1M: 1.25,
    canonicalSlug: "openai/gpt-5.6-terra-pro-20260709",
    created: 1783590861,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+file->text",
      inputModalities: <String>["file", "image", "text"],
      outputModalities: <String>["text"],
      tokenizer: "GPT",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_completion_tokens",
      "max_tokens",
      "reasoning",
      "reasoning_effort",
      "response_format",
      "seed",
      "structured_outputs",
      "tool_choice",
      "tools",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    knowledgeCutoff: "2026-02-16",
    links: AiModelLinksMetadata(
      details: "/api/v1/models/openai/gpt-5.6-terra-pro-20260709/endpoints",
    ),
  ),
  "openrouter/auto-beta": AiModelProfile(
    displayName: "Auto Router (Beta)",
    description:
        "Auto Router (Beta) is a task-aware router from OpenRouter. It classifies each request, then routes it the [most popular model](/rankings#task-spend) for that task based on aggregate spend, filtered by your...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.audio,
      AiModelModality.file,
      AiModelModality.image,
      AiModelModality.text,
      AiModelModality.video,
    },
    maxContextLength: 2000000,
    capabilities: <AiModelCapability>{AiModelCapability.imageGeneration},
    canonicalSlug: "openrouter/auto-beta",
    created: 1784311165,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+file+audio+video->text+image",
      inputModalities: <String>["text", "image", "audio", "file", "video"],
      outputModalities: <String>["text", "image"],
      tokenizer: "Router",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "include_reasoning",
      "logit_bias",
      "logprobs",
      "max_tokens",
      "min_p",
      "prediction",
      "presence_penalty",
      "reasoning",
      "reasoning_effort",
      "repetition_penalty",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_a",
      "top_k",
      "top_logprobs",
      "top_p",
      "web_search_options",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/openrouter/auto-beta/endpoints",
    ),
  ),
  "openrouter/fusion": AiModelProfile(
    displayName: "Fusion",
    description:
        "Fusion turns your prompt into a small multi-model deliberation. A panel of expert models (see below) analyzes your prompt in parallel with web search and web fetch enabled, then a...",
    supportedModalities: <AiModelModality>{AiModelModality.text},
    maxContextLength: 1000000,
    canonicalSlug: "openrouter/fusion",
    created: 1781371647,
    architecture: AiModelArchitectureMetadata(
      modality: "text->text",
      inputModalities: <String>["text"],
      outputModalities: <String>["text"],
      tokenizer: "Router",
    ),
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/openrouter/fusion/endpoints",
    ),
  ),
  "poolside/laguna-s-2.1": AiModelProfile(
    displayName: "Laguna S 2.1",
    description:
        "Laguna S 2.1 is the latest coding agent model from [Poolside](<https://poolside.ai/>). Laguna S 2.1 is a 118B total parameter model with 8B active parameters, scoring 70.2% on Terminal-Bench 2.1 and...",
    supportedModalities: <AiModelModality>{AiModelModality.text},
    maxContextLength: 1048576,
    maxOutputLength: 131072,
    maxThinkingLength: 131072,
    thinkingEnabled: true,
    inputUsdPer1M: 0.09,
    outputUsdPer1M: 0.18,
    cacheReadUsdPer1M: 0.009,
    canonicalSlug: "poolside/laguna-s-2.1-20260720",
    huggingFaceId: "poolside/Laguna-S-2.1",
    created: 1784652683,
    architecture: AiModelArchitectureMetadata(
      modality: "text->text",
      inputModalities: <String>["text"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "temperature",
      "tool_choice",
      "tools",
    ],
    links: AiModelLinksMetadata(
      details: "/api/v1/models/poolside/laguna-s-2.1-20260720/endpoints",
    ),
  ),
  "poolside/laguna-s-2.1:free": AiModelProfile(
    displayName: "Laguna S 2.1 (free)",
    description:
        "Laguna S 2.1 is the latest coding agent model from [Poolside](<https://poolside.ai/>). Laguna S 2.1 is a 118B total parameter model with 8B active parameters, scoring 70.2% on Terminal-Bench 2.1 and...",
    supportedModalities: <AiModelModality>{AiModelModality.text},
    maxContextLength: 262144,
    maxOutputLength: 32768,
    maxThinkingLength: 32768,
    thinkingEnabled: true,
    inputUsdPer1M: 0,
    outputUsdPer1M: 0,
    canonicalSlug: "poolside/laguna-s-2.1-20260720",
    huggingFaceId: "poolside/Laguna-S-2.1",
    created: 1784652683,
    architecture: AiModelArchitectureMetadata(
      modality: "text->text",
      inputModalities: <String>["text"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "temperature",
      "tool_choice",
      "tools",
    ],
    links: AiModelLinksMetadata(
      details: "/api/v1/models/poolside/laguna-s-2.1-20260720/endpoints",
    ),
  ),
  "poolside/laguna-xs-2.1": AiModelProfile(
    displayName: "Laguna XS 2.1",
    description:
        "Laguna XS 2.1 is the latest coding agent model in the 33B-A3B category from [Poolside](https://poolside.ai/) and a step forward from their Laguna XS.2 model (released in April 2026). It combines...",
    supportedModalities: <AiModelModality>{AiModelModality.text},
    maxContextLength: 262144,
    maxOutputLength: 32768,
    maxThinkingLength: 32768,
    thinkingEnabled: true,
    inputUsdPer1M: 0.06,
    outputUsdPer1M: 0.12,
    cacheReadUsdPer1M: 0.03,
    canonicalSlug: "poolside/laguna-xs-2.1-20260625",
    huggingFaceId: "poolside/Laguna-XS-2.1",
    created: 1783002429,
    architecture: AiModelArchitectureMetadata(
      modality: "text->text",
      inputModalities: <String>["text"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "temperature",
      "tool_choice",
      "tools",
    ],
    links: AiModelLinksMetadata(
      details: "/api/v1/models/poolside/laguna-xs-2.1-20260625/endpoints",
    ),
  ),
  "poolside/laguna-xs-2.1:free": AiModelProfile(
    displayName: "Laguna XS 2.1 (free)",
    description:
        "Laguna XS 2.1 is the latest coding agent model in the 33B-A3B category from [Poolside](https://poolside.ai/) and a step forward from their Laguna XS.2 model (released in April 2026). It combines...",
    supportedModalities: <AiModelModality>{AiModelModality.text},
    maxContextLength: 262144,
    maxOutputLength: 32768,
    maxThinkingLength: 32768,
    thinkingEnabled: true,
    inputUsdPer1M: 0,
    outputUsdPer1M: 0,
    canonicalSlug: "poolside/laguna-xs-2.1-20260625",
    huggingFaceId: "poolside/Laguna-XS-2.1",
    created: 1783002429,
    architecture: AiModelArchitectureMetadata(
      modality: "text->text",
      inputModalities: <String>["text"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_tokens",
      "reasoning",
      "temperature",
      "tool_choice",
      "tools",
    ],
    links: AiModelLinksMetadata(
      details: "/api/v1/models/poolside/laguna-xs-2.1-20260625/endpoints",
    ),
  ),
  "qwen/qwen3.7-flash": AiModelProfile(
    displayName: "Qwen3.7 Flash",
    description:
        "Qwen3.7 Flash is a vision-language reasoning model from Alibaba. It is suited for multimodal agents, visual coding, search, and computer interaction, with strengths in object recognition, spatial understanding, and real-world...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.image,
      AiModelModality.text,
      AiModelModality.video,
    },
    maxContextLength: 1000000,
    maxOutputLength: 65536,
    maxThinkingLength: 65536,
    thinkingEnabled: true,
    inputUsdPer1M: 0.03,
    outputUsdPer1M: 0.13,
    cacheReadUsdPer1M: 0.006,
    cacheWriteUsdPer1M: 0.038,
    canonicalSlug: "qwen/qwen3.7-flash-20260727",
    created: 1785190561,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+video->text",
      inputModalities: <String>["text", "image", "video"],
      outputModalities: <String>["text"],
      tokenizer: "Qwen",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "logprobs",
      "max_tokens",
      "presence_penalty",
      "reasoning",
      "response_format",
      "seed",
      "temperature",
      "tool_choice",
      "tools",
      "top_logprobs",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/qwen/qwen3.7-flash-20260727/endpoints",
    ),
  ),
  "qwen/qwen3.7-plus": AiModelProfile(
    displayName: "Qwen3.7 Plus",
    description:
        "Qwen3.7-Plus is a cost-effective model in Alibaba's Qwen3.7 series. It supports text and image input with text output, building on the series' text capabilities with a comprehensive upgrade to its...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 1000000,
    maxOutputLength: 131072,
    maxThinkingLength: 131072,
    thinkingEnabled: true,
    inputUsdPer1M: 0.32,
    outputUsdPer1M: 1.28,
    cacheReadUsdPer1M: 0.064,
    cacheWriteUsdPer1M: 0.4,
    canonicalSlug: "qwen/qwen3.7-plus-20260602",
    created: 1780491783,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image->text",
      inputModalities: <String>["text", "image"],
      outputModalities: <String>["text"],
      tokenizer: "Qwen",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "include_reasoning",
      "logprobs",
      "max_tokens",
      "presence_penalty",
      "reasoning",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_logprobs",
      "top_p",
    ],
    links: AiModelLinksMetadata(
      details: "/api/v1/models/qwen/qwen3.7-plus-20260602/endpoints",
    ),
  ),
  "qwen/qwen3.8-max": AiModelProfile(
    displayName: "Qwen3.8 Max",
    description:
        "Qwen3.8 Max is the flagship model in Alibaba's Qwen3.8 series, the general-availability successor to the Qwen3.8 Max Preview. It is a multimodal reasoning model intended for complex reasoning, visual understanding,...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.image,
      AiModelModality.text,
      AiModelModality.video,
    },
    maxContextLength: 1000000,
    maxOutputLength: 131072,
    maxThinkingLength: 131072,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "xhigh",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["xhigh", "high", "medium", "low", "minimal"],
    ),
    inputUsdPer1M: 2,
    outputUsdPer1M: 6,
    cacheReadUsdPer1M: 0.25,
    cacheWriteUsdPer1M: 2.5,
    canonicalSlug: "qwen/qwen3.8-max-20260803",
    created: 1785731612,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+video->text",
      inputModalities: <String>["text", "image", "video"],
      outputModalities: <String>["text"],
      tokenizer: "Qwen",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "include_reasoning",
      "logprobs",
      "max_tokens",
      "presence_penalty",
      "reasoning",
      "reasoning_effort",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_logprobs",
      "top_p",
    ],
    links: AiModelLinksMetadata(
      details: "/api/v1/models/qwen/qwen3.8-max-20260803/endpoints",
    ),
  ),
  "sakana/fugu-ultra": AiModelProfile(
    displayName: "Fugu Ultra",
    description:
        "Fugu Ultra is the higher-performance model in Sakana AI's Fugu family. Rather than a single monolithic model, Fugu is a learned multi-agent orchestration system: a language model trained to route...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 1000000,
    maxOutputLength: 128000,
    maxThinkingLength: 128000,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "xhigh",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["max", "xhigh", "high"],
    ),
    inputUsdPer1M: 5,
    outputUsdPer1M: 30,
    cacheReadUsdPer1M: 0.5,
    canonicalSlug: "sakana/fugu-ultra-20260615",
    created: 1782276303,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image->text",
      inputModalities: <String>["text", "image"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "reasoning",
      "reasoning_effort",
      "structured_outputs",
      "tool_choice",
      "tools",
      "web_search_options",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/sakana/fugu-ultra-20260615/endpoints",
    ),
  ),
  "tencent/hy3": AiModelProfile(
    displayName: "Hy3",
    description:
        "Hy3 is a 295B-parameter Mixture-of-Experts model from Tencent (21B active, 192 experts with top-8 routing) built for reasoning, agentic workflows, and real-world production use. It supports a configurable reasoning effort:...",
    supportedModalities: <AiModelModality>{AiModelModality.text},
    maxContextLength: 262144,
    maxOutputLength: 128000,
    maxThinkingLength: 128000,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "high",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["high", "low", "none"],
    ),
    inputUsdPer1M: 0.132,
    outputUsdPer1M: 0.528,
    cacheReadUsdPer1M: 0.033,
    canonicalSlug: "tencent/hy3-20260706",
    huggingFaceId: "tencent/Hy3",
    created: 1783344048,
    architecture: AiModelArchitectureMetadata(
      modality: "text->text",
      inputModalities: <String>["text"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "include_reasoning",
      "logit_bias",
      "max_completion_tokens",
      "max_tokens",
      "min_p",
      "presence_penalty",
      "reasoning",
      "reasoning_effort",
      "repetition_penalty",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": 0.9,
      "top_p": 1,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/tencent/hy3-20260706/endpoints",
    ),
  ),
  "thinkingmachines/inkling": AiModelProfile(
    displayName: "Inkling",
    description:
        "Inkling is an open-weight multimodal mixture-of-experts model from Thinking Machines Lab, with 41B active parameters out of 975B total. It is designed for general-purpose reasoning, coding, agentic and tool-use systems,...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.audio,
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 1048576,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "high",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["max", "high", "medium", "low", "minimal", "none"],
    ),
    inputUsdPer1M: 1,
    outputUsdPer1M: 4.05,
    cacheReadUsdPer1M: 0.17,
    canonicalSlug: "thinkingmachines/inkling-20260715",
    huggingFaceId: "thinkingmachines/Inkling",
    created: 1784325956,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+audio->text",
      inputModalities: <String>["text", "image", "audio"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "include_reasoning",
      "logit_bias",
      "max_tokens",
      "min_p",
      "presence_penalty",
      "reasoning",
      "reasoning_effort",
      "repetition_penalty",
      "response_format",
      "seed",
      "stop",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/thinkingmachines/inkling-20260715/endpoints",
    ),
  ),
  "thinkingmachines/inkling-small": AiModelProfile(
    displayName: "Inkling Small",
    description:
        "Inkling Small is an open-weight multimodal mixture-of-experts model from Thinking Machines Lab, with 12B active parameters out of 276B total. It is positioned as the smaller, more efficient member of...",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.audio,
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 524288,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "high",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["max", "high", "medium", "low", "minimal", "none"],
    ),
    inputUsdPer1M: 0.5,
    outputUsdPer1M: 1.2,
    cacheReadUsdPer1M: 0.1,
    canonicalSlug: "thinkingmachines/inkling-small-20260730",
    huggingFaceId: "thinkingmachines/Inkling-Small",
    created: 1785443117,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+audio->text",
      inputModalities: <String>["text", "image", "audio"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "include_reasoning",
      "logit_bias",
      "logprobs",
      "max_tokens",
      "min_p",
      "presence_penalty",
      "reasoning",
      "reasoning_effort",
      "repetition_penalty",
      "seed",
      "stop",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_logprobs",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details:
          "/api/v1/models/thinkingmachines/inkling-small-20260730/endpoints",
    ),
  ),
  "x-ai/grok-4.5": AiModelProfile(
    displayName: "Grok 4.5",
    description:
        "Grok 4.5 is SpaceXAI's smartest model with frontier performance on coding, knowledge work, and STEM.",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.file,
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 500000,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "high",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["high", "medium", "low", "xhigh"],
    ),
    inputUsdPer1M: 2,
    outputUsdPer1M: 6,
    cacheReadUsdPer1M: 0.3,
    canonicalSlug: "x-ai/grok-4.5-20260708",
    created: 1783523154,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+file->text",
      inputModalities: <String>["text", "image", "file"],
      outputModalities: <String>["text"],
      tokenizer: "Grok",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "include_reasoning",
      "logprobs",
      "max_tokens",
      "presence_penalty",
      "reasoning",
      "reasoning_effort",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_logprobs",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/x-ai/grok-4.5-20260708/endpoints",
    ),
  ),
  "z-ai/glm-5.2": AiModelProfile(
    displayName: "GLM 5.2",
    description:
        "GLM 5.2 is a large-scale reasoning model from Z.ai. It supports text input and output with a 1M-token context window, and is suited for long-horizon agent workflows, project-level software engineering,...",
    supportedModalities: <AiModelModality>{AiModelModality.text},
    maxContextLength: 1048576,
    maxOutputLength: 262144,
    maxThinkingLength: 262144,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "high",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["xhigh", "high"],
    ),
    inputUsdPer1M: 0.76,
    outputUsdPer1M: 2.42,
    cacheReadUsdPer1M: 0.14,
    canonicalSlug: "z-ai/glm-5.2-20260616",
    huggingFaceId: "zai-org/GLM-5.2",
    created: 1781631930,
    architecture: AiModelArchitectureMetadata(
      modality: "text->text",
      inputModalities: <String>["text"],
      outputModalities: <String>["text"],
      tokenizer: "Other",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "include_reasoning",
      "logit_bias",
      "logprobs",
      "max_tokens",
      "min_p",
      "parallel_tool_calls",
      "presence_penalty",
      "reasoning",
      "reasoning_effort",
      "repetition_penalty",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_k",
      "top_logprobs",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": 1,
      "top_p": 0.95,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/z-ai/glm-5.2-20260616/endpoints",
    ),
  ),
  "~anthropic/claude-fable-latest": AiModelProfile(
    displayName: "Claude Fable Latest",
    description:
        "This model always redirects to the latest model in the Claude Fable family.",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.file,
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 1000000,
    maxOutputLength: 128000,
    maxThinkingLength: 128000,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "high",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["max", "xhigh", "high", "medium", "low"],
    ),
    inputUsdPer1M: 10,
    outputUsdPer1M: 50,
    cacheReadUsdPer1M: 1,
    cacheWriteUsdPer1M: 12.5,
    canonicalSlug: "~anthropic/claude-fable-latest",
    created: 1781029944,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+file->text",
      inputModalities: <String>["text", "image", "file"],
      outputModalities: <String>["text"],
      tokenizer: "Router",
    ),
    supportedParameters: <String>[
      "include_reasoning",
      "max_completion_tokens",
      "max_tokens",
      "reasoning",
      "reasoning_effort",
      "response_format",
      "stop",
      "structured_outputs",
      "tool_choice",
      "tools",
      "verbosity",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/~anthropic/claude-fable-latest/endpoints",
    ),
  ),
  "~deepseek/deepseek-v4-flash-latest": AiModelProfile(
    displayName: "DeepSeek V4 Flash Latest",
    description:
        "This model always redirects to the latest model in the DeepSeek V4 Flash family.",
    supportedModalities: <AiModelModality>{AiModelModality.text},
    maxContextLength: 1048576,
    maxOutputLength: 65536,
    maxThinkingLength: 65536,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "high",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["max", "high", "low"],
    ),
    inputUsdPer1M: 0.09,
    outputUsdPer1M: 0.18,
    cacheReadUsdPer1M: 0.018,
    canonicalSlug: "~deepseek/deepseek-v4-flash-latest",
    created: 1785606009,
    architecture: AiModelArchitectureMetadata(
      modality: "text->text",
      inputModalities: <String>["text"],
      outputModalities: <String>["text"],
      tokenizer: "Router",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "include_reasoning",
      "logit_bias",
      "logprobs",
      "max_tokens",
      "min_p",
      "presence_penalty",
      "reasoning",
      "reasoning_effort",
      "repetition_penalty",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_a",
      "top_k",
      "top_logprobs",
      "top_p",
    ],
    links: AiModelLinksMetadata(
      details: "/api/v1/models/~deepseek/deepseek-v4-flash-latest/endpoints",
    ),
  ),
  "~x-ai/grok-latest": AiModelProfile(
    displayName: "Grok Latest",
    description:
        "This model always redirects to the latest Grok model from xAI.",
    isMultimodal: true,
    supportsAttachments: true,
    supportedModalities: <AiModelModality>{
      AiModelModality.file,
      AiModelModality.image,
      AiModelModality.text,
    },
    maxContextLength: 500000,
    thinkingEnabled: true,
    reasoningEffortControlEnabled: true,
    reasoningEffort: "high",
    reasoningEffortOptions: AiReasoningEffortOption.standardValues(
      const <String>["high", "medium", "low"],
    ),
    inputUsdPer1M: 2,
    outputUsdPer1M: 6,
    cacheReadUsdPer1M: 0.3,
    canonicalSlug: "~x-ai/grok-latest",
    created: 1783519360,
    architecture: AiModelArchitectureMetadata(
      modality: "text+image+file->text",
      inputModalities: <String>["text", "image", "file"],
      outputModalities: <String>["text"],
      tokenizer: "Router",
    ),
    supportedParameters: <String>[
      "frequency_penalty",
      "include_reasoning",
      "logprobs",
      "max_tokens",
      "presence_penalty",
      "reasoning",
      "reasoning_effort",
      "response_format",
      "seed",
      "stop",
      "structured_outputs",
      "temperature",
      "tool_choice",
      "tools",
      "top_logprobs",
      "top_p",
    ],
    defaultParameters: <String, Object?>{
      "temperature": null,
      "top_p": null,
      "top_k": null,
      "frequency_penalty": null,
      "presence_penalty": null,
      "repetition_penalty": null,
    },
    links: AiModelLinksMetadata(
      details: "/api/v1/models/~x-ai/grok-latest/endpoints",
    ),
  ),
};
