import 'package:flutter/widgets.dart';
import '../../l10n/app_localizations.dart';

/// 仅转换运维界面字段与状态，机器数据和原始输出保持原样。
String maintenanceLabel(BuildContext context, String label) {
  final l10n = AppLocalizations.of(context)!;
  label = switch (label) {
    'Running' => '运行中',
    'Stopped' => '未运行',
    'Paused' => '暂停',
    'LISTENING' => 'LISTEN',
    'SYN_RECEIVED' => 'SYN_RECV',
    'SYN_RCVD' => 'SYN_RECV',
    'FIN_WAIT_1' => 'FIN_WAIT1',
    'FIN_WAIT_2' => 'FIN_WAIT2',
    _ => label,
  };
  return switch (label) {
    "服务器运维中心" => l10n.maintenanceCenter,
    "服务器运维" => l10n.maintenanceEntry,
    "运行总览" => l10n.maintenanceOverview,
    "进程管理" => l10n.maintenanceProcesses,
    "系统服务" => l10n.maintenanceServices,
    "网络与诊断" => l10n.maintenanceNetworkDiagnostics,
    "系统与内核" => l10n.maintenanceSystemKernel,
    "处理器型号" => l10n.maintenanceProcessorModel,
    "系统负载 · 1 / 5 / 15 分钟" => l10n.maintenanceLoadIntervals,
    "资源压力 · CPU / 内存 / IO" => l10n.maintenancePressure,
    "文件系统容量 · KiB" => l10n.maintenanceFilesystemCapacity,
    "文件系统 inode" => l10n.maintenanceInodes,
    "交换空间" => l10n.maintenanceSwapSpace,
    "网卡链路与硬件" => l10n.maintenanceInterfaces,
    "温度传感器" => l10n.maintenanceSensors,
    "内存详情" => l10n.maintenanceMemoryDetails,
    "内存统计口径" => l10n.maintenanceMemoryBasis,
    "内存与分页性能计数器" => l10n.maintenanceMemoryCounters,
    "虚拟内存计数器" => l10n.maintenanceVmCounters,
    "开机启动状态" => l10n.maintenanceStartup,
    "系统定时器" => l10n.maintenanceTimers,
    "连接与监听端口" => l10n.maintenanceSockets,
    "地址与路由" => l10n.maintenanceRoutes,
    "DNS 配置" => l10n.maintenanceDns,
    "最近日志" => l10n.maintenanceLogs,
    "登录用户" => l10n.maintenanceUsers,
    "当前用户计划任务" => l10n.maintenanceCron,
    "防火墙规则" => l10n.maintenanceFirewall,
    "容器状态" => l10n.maintenanceContainers,
    "状态详情" => l10n.maintenanceStatusDetails,
    "启动命令" => l10n.maintenanceCommand,
    "可执行文件与工作目录" => l10n.maintenancePaths,
    "进程 IO 计数器" => l10n.maintenanceProcessIo,
    "资源限制" => l10n.maintenanceLimits,
    "控制组" => l10n.maintenanceCgroup,
    "打开的文件描述符" => l10n.maintenanceDescriptors,
    "环境能力" => l10n.maintenanceCapabilities,
    "块设备与 RAID" => l10n.maintenanceBlocks,
    "控制组资源限制 · 容器与主机视图可能不同" => l10n.maintenanceCgroupLimits,
    "内核资源参数" => l10n.maintenanceKernel,
    "网卡累计计数 · 字节、包、错误与丢包" => l10n.maintenanceNetworkCounters,
    "采集中" => l10n.maintenanceCollecting,
    "采集异常" => l10n.maintenanceCollectionError,
    "自动刷新" => l10n.maintenanceAutoRefresh,
    "手动刷新" => l10n.maintenanceManualRefresh,
    "正在识别目标系统" => l10n.maintenanceDetecting,
    "自动识别 Shell" => l10n.maintenanceAutoShell,
    "终端 Shell" => l10n.maintenanceShell,
    "自动刷新间隔" => l10n.maintenanceInterval,
    "等待首次采样" => l10n.maintenanceFirstSample,
    "暂停自动刷新" => l10n.maintenancePauseRefresh,
    "开启自动刷新（当前分区）" => l10n.maintenanceStartRefresh,
    "刷新当前分区" => l10n.maintenanceRefreshSection,
    "当前终端 · 辅助命令不持久化 · 速率需两次采样" => l10n.maintenanceFooter,
    "正在连接当前终端" => l10n.maintenanceConnecting,
    "机器状态暂不可用" => l10n.maintenanceUnavailableHost,
    "识别系统并读取运行状态" => l10n.maintenanceIdentifying,
    "未能完成本次采集" => l10n.maintenanceCollectionFailed,
    "数据就绪后将显示资源、进程、服务与网络状态。" => l10n.maintenanceLoadingHelp,
    "请确认终端已连接并处于命令提示符，再重新采集。" => l10n.maintenanceRetryHelp,
    "重新采集" => l10n.maintenanceRetry,
    "内存" => l10n.maintenanceMemory,
    "磁盘" => l10n.maintenanceDisk,
    "网络" => l10n.maintenanceNetwork,
    "等待目标机器数据" => l10n.maintenanceWaitingData,
    "当前采样 · 完整原始内容" => l10n.maintenanceRawSample,
    "资源使用" => l10n.maintenanceResourceUse,
    "运行时间" => l10n.maintenanceUptime,
    "负载均衡" => l10n.maintenanceLoad,
    "处理器" => l10n.maintenanceProcessor,
    "采样状态" => l10n.maintenanceSampleStatus,
    "数据可能过期" => l10n.maintenanceStale,
    "采集成功" => l10n.maintenanceCollected,
    "刷新方式" => l10n.maintenanceRefreshMode,
    "趋势样本" => l10n.maintenanceTrendSamples,
    "目标平台" => l10n.maintenanceTargetPlatform,
    "速率根据连续采样计算；不可用字段不作推断。" => l10n.maintenanceRateHelp,
    "每核负载" => l10n.maintenancePerCore,
    "基本信息" => l10n.maintenanceBasicInfo,
    "系统原始信息" => l10n.maintenanceRawSystem,
    "主机名" => l10n.maintenanceHost,
    "操作系统" => l10n.maintenanceOs,
    "系统版本" => l10n.maintenanceOsVersion,
    "内核版本" => l10n.maintenanceKernelVersion,
    "逻辑处理器" => l10n.maintenanceLogicalCpus,
    "存储空间" => l10n.maintenanceStorage,
    "文件系统" => l10n.maintenanceFilesystem,
    "暂无可读的文件系统" => l10n.maintenanceNoFilesystem,
    "网络吞吐" => l10n.maintenanceThroughput,
    "网卡详情" => l10n.maintenanceInterfaceDetails,
    "网卡" => l10n.maintenanceInterface,
    "接收 / 秒" => l10n.maintenanceReceiveRate,
    "发送 / 秒" => l10n.maintenanceSendRate,
    "CPU 实时趋势" => l10n.maintenanceCpuTrend,
    "正在积累样本…" => l10n.maintenanceAccumulating,
    "开启自动刷新后显示趋势" => l10n.maintenanceTrendHelp,
    "运维操作" => l10n.maintenanceOperations,
    "查看进程" => l10n.maintenanceViewProcesses,
    "管理系统服务" => l10n.maintenanceManageServices,
    "网络诊断" => l10n.maintenanceNetworkAction,
    "资源提醒" => l10n.maintenanceAlerts,
    "暂无阈值提醒" => l10n.maintenanceNoAlerts,
    "依据当前 CPU 与内存采样，提醒阈值 85%；磁盘完整信息可在详情查看。" => l10n.maintenanceAlertHelp,
    "CPU 使用率" => l10n.maintenanceCpuUsage,
    "内存使用率" => l10n.maintenanceMemoryUsage,
    "暂无数据" => l10n.maintenanceNoData,
    "SWAP 使用量" => l10n.maintenanceSwapUsage,
    "未配置交换空间" => l10n.maintenanceNoSwap,
    "更多系统指标" => l10n.maintenanceMoreMetrics,
    "磁盘 IO" => l10n.maintenanceDiskIo,
    "设备" => l10n.maintenanceDevice,
    "读取 / 秒" => l10n.maintenanceReadRate,
    "写入 / 秒" => l10n.maintenanceWriteRate,
    "读 IOPS" => l10n.maintenanceReadIops,
    "写 IOPS" => l10n.maintenanceWriteIops,
    "当前环境未提供可用计数器。" => l10n.maintenanceNoCounters,
    "搜索 PID 或进程名" => l10n.maintenanceSearchProcess,
    "CPU 降序" => l10n.maintenanceSortCpu,
    "内存降序" => l10n.maintenanceSortMemory,
    "PID 升序" => l10n.maintenanceSortPid,
    "进程" => l10n.maintenanceProcess,
    "状态" => l10n.maintenanceStatus,
    "CPU / 单核" => l10n.maintenanceCpuPerCore,
    "驻留内存" => l10n.maintenanceResidentMemory,
    "线程" => l10n.maintenanceThreads,
    "不可用" => l10n.maintenanceUnavailable,
    "上一批进程" => l10n.maintenancePreviousBatch,
    "下一批进程" => l10n.maintenanceNextBatch,
    "运行中" => l10n.maintenanceRunning,
    "未运行" => l10n.maintenanceStopped,
    "未知" => l10n.maintenanceUnknown,
    "异常" => l10n.maintenanceFailed,
    "待检查" => l10n.maintenanceUnchecked,
    "已发现服务" => l10n.maintenanceDiscoveredServices,
    "当前可见服务" => l10n.maintenanceVisibleServices,
    "异常服务" => l10n.maintenanceFailedServices,
    "仅统计明确报告失败的条目" => l10n.maintenanceFailedServiceHelp,
    "筛选服务" => l10n.maintenanceSearchService,
    "未解析到 TCP / UDP 连接，可查看原始数据。" => l10n.maintenanceNoConnections,
    "协议" => l10n.maintenanceProtocol,
    "本地地址" => l10n.maintenanceLocalAddress,
    "远端地址" => l10n.maintenanceRemoteAddress,
    "DNS 服务器" => l10n.maintenanceDnsServers,
    "暂无可解析的服务器地址" => l10n.maintenanceNoDns,
    "诊断项目" => l10n.maintenanceDiagnosticItems,
    "已解析连接" => l10n.maintenanceParsedConnections,
    "当前采样中的 TCP / UDP" => l10n.maintenanceConnectionHelp,
    "解析自当前系统配置" => l10n.maintenanceDnsHelp,
    "路由、日志、任务与安全" => l10n.maintenanceDiagnosticHelp,
    "未提供" => l10n.maintenanceNotProvided,
    "运行" => l10n.maintenanceProcessRunning,
    "休眠" => l10n.maintenanceSleeping,
    "空闲" => l10n.maintenanceIdle,
    "暂停" => l10n.maintenanceSuspended,
    "僵尸" => l10n.maintenanceZombie,
    "IO 等待" => l10n.maintenanceIoWait,
    "部分不可用 · 查看原因" => l10n.maintenancePartial,
    "已采集 · 查看详情" => l10n.maintenanceViewCollected,
    "暂无可用数据" => l10n.maintenanceNoAvailableData,
    "查看详情" => l10n.maintenanceViewDetails,
    "确认执行" => l10n.maintenanceConfirm,
    "实时详情 · 部分字段需要更高权限" => l10n.maintenanceDetailSubtitle,
    "刷新详情" => l10n.maintenanceRefreshDetails,
    "正在读取详情…" => l10n.maintenanceLoadingDetails,
    "读取失败，请重试。" => l10n.maintenanceDetailsFailed,
    "终止进程" => l10n.maintenanceTerminate,
    "暂停进程" => l10n.maintenanceSuspend,
    "恢复进程" => l10n.maintenanceResume,
    "启动服务" => l10n.maintenanceStartService,
    "停止服务" => l10n.maintenanceStopService,
    "重启服务" => l10n.maintenanceRestartService,
    "启用开机启动" => l10n.maintenanceEnableStartup,
    "禁用开机启动" => l10n.maintenanceDisableStartup,
    "自动启动" => l10n.maintenanceAutomaticStartup,
    "手动启动" => l10n.maintenanceManualStartup,
    "禁用服务" => l10n.maintenanceDisableService,
    "所选 Shell 与目标系统不匹配，请改为自动识别或实际使用的 Shell。" => l10n.maintenanceShellMismatch,
    "ESTABLISHED" => l10n.maintenanceEstablished,
    "LISTEN" => l10n.maintenanceListening,
    "CLOSE_WAIT" => l10n.maintenanceCloseWait,
    "CLOSING" => l10n.maintenanceClosing,
    "TIME_WAIT" => l10n.maintenanceTimeWait,
    "SYN_SENT" => l10n.maintenanceSynSent,
    "SYN_RECV" => l10n.maintenanceSynReceived,
    "CLOSED" => l10n.maintenanceClosed,
    "LAST_ACK" => l10n.maintenanceLastAck,
    "FIN_WAIT1" => l10n.maintenanceFinWait1,
    "FIN_WAIT2" => l10n.maintenanceFinWait2,
    "UNCONN" => l10n.maintenanceUnconnected,
    "Start Pending" => l10n.maintenanceServiceStarting,
    "Stop Pending" => l10n.maintenanceServiceStopping,
    "ProductName" => l10n.maintenanceProductName,
    "ProductVersion" => l10n.maintenanceProductVersion,
    "BuildVersion" => l10n.maintenanceBuildVersion,
    "Routing tables" => l10n.maintenanceRoutingTables,
    "DNS configuration" => l10n.maintenanceDnsConfiguration,
    "Active Internet connections" => l10n.maintenanceActiveInternet,
    "Active Multipath Internet connections" => l10n.maintenanceActiveMultipath,
    "Active LOCAL (UNIX) domain sockets" => l10n.maintenanceActiveUnix,
    "nameserver" => l10n.maintenanceNameserver,
    "resolver" => l10n.maintenanceResolver,
    "if_index" => l10n.maintenanceIfIndex,
    "flags" => l10n.maintenanceFlags,
    "reach" => l10n.maintenanceReach,
    "本地化字段" => l10n.maintenanceLocalizedFields,
    "原始输出" => l10n.maintenanceOriginalOutput,
    "目的地址" => l10n.maintenanceDestination,
    "网关" => l10n.maintenanceGateway,
    "过期时间" => l10n.maintenanceExpires,
    "接收队列" => l10n.maintenanceReceiveQueue,
    "发送队列" => l10n.maintenanceSendQueue,
    "地址" => l10n.maintenanceAddress,
    "类型" => l10n.maintenanceType,
    "名称" => l10n.maintenanceName,
    "描述" => l10n.maintenanceDescription,
    "父进程 ID" => l10n.maintenanceParentPid,
    "用户 ID" => l10n.maintenanceUserId,
    "组 ID" => l10n.maintenanceGroupId,
    "优先级" => l10n.maintenancePriority,
    "虚拟内存" => l10n.maintenanceVirtualMemory,
    "启动方式" => l10n.maintenanceStartMode,
    "退出代码" => l10n.maintenanceExitCode,
    "路径" => l10n.maintenancePath,
    "架构" => l10n.maintenanceArchitecture,
    "可用内存" => l10n.maintenanceAvailableMemory,
    "空闲内存" => l10n.maintenanceFreeMemory,
    "内存总量" => l10n.maintenanceTotalMemory,
    "缓存内存" => l10n.maintenanceCachedMemory,
    "缓冲区内存" => l10n.maintenanceBufferMemory,
    "读取字节" => l10n.maintenanceBytesRead,
    "写入字节" => l10n.maintenanceBytesWritten,
    "接收字节" => l10n.maintenanceReceiveBytes,
    "发送字节" => l10n.maintenanceSendBytes,
    _ => label,
  };
}

/// 只识别已知字段名和表头，不替换日志正文、地址、路径或其他值。
String maintenanceLocalizedOutput(BuildContext context, String output) {
  const fields = {
    'ProductName': 'ProductName',
    'ProductVersion': 'ProductVersion',
    'BuildVersion': 'BuildVersion',
    'nameserver': 'nameserver',
    'resolver': 'resolver',
    'if_index': 'if_index',
    'flags': 'flags',
    'reach': 'reach',
    'Name': '名称',
    'Caption': '名称',
    'Description': '描述',
    'State': '状态',
    'Status': '状态',
    'Threads': '线程',
    'ThreadCount': '线程',
    'PPid': '父进程 ID',
    'ParentProcessId': '父进程 ID',
    'Uid': '用户 ID',
    'Gid': '组 ID',
    'Priority': '优先级',
    'VmRSS': '驻留内存',
    'WorkingSetSize': '驻留内存',
    'VmSize': '虚拟内存',
    'VirtualSize': '虚拟内存',
    'StartMode': '启动方式',
    'ExitCode': '退出代码',
    'PathName': '路径',
    'ExecutablePath': '路径',
    'CommandLine': '启动命令',
    'OSArchitecture': '架构',
    'MemTotal': '内存总量',
    'MemFree': '空闲内存',
    'MemAvailable': '可用内存',
    'Cached': '缓存内存',
    'Buffers': '缓冲区内存',
    'read_bytes': '读取字节',
    'write_bytes': '写入字节',
    'rchar': '读取字节',
    'wchar': '写入字节',
  };
  const headings = {
    'Destination': '目的地址',
    'Gateway': '网关',
    'Flags': 'flags',
    'Netif': '网卡',
    'Iface': '网卡',
    'Expire': '过期时间',
    'Proto': '协议',
    'Proto/ID': '协议',
    'Recv-Q': '接收队列',
    'Send-Q': '发送队列',
    'Local Address': '本地地址',
    'Foreign Address': '远端地址',
    '(state)': '状态',
    'Address': '地址',
    'Type': '类型',
  };
  return output
      .split('\n')
      .map((line) {
        final trimmed = line.trim();
        if (const [
          'Routing tables',
          'DNS configuration',
          'Active Internet connections',
          'Active Multipath Internet connections',
          'Active LOCAL (UNIX) domain sockets',
        ].contains(trimmed)) {
          return maintenanceLabel(context, trimmed);
        }
        final field = RegExp(
          r'^(\s*)([A-Za-z_]+)(\[\d+\]| #\d+)?(\s*[:=].*|\s*)$',
        ).firstMatch(line);
        if (field != null && fields.containsKey(field[2])) {
          return '${field[1]}${maintenanceLabel(context, fields[field[2]]!)}${field[3] ?? ''}${field[4]}';
        }
        if (RegExp(
          r'^\s*(Destination\s+Gateway|Proto(?:/ID)?\s+|Address\s+Type)',
        ).hasMatch(line)) {
          for (final entry in headings.entries) {
            line = line.replaceAllMapped(
              RegExp('(?<![A-Za-z])${RegExp.escape(entry.key)}(?![A-Za-z])'),
              (_) => maintenanceLabel(context, entry.value),
            );
          }
        }
        return line;
      })
      .join('\n');
}
