import 'package:flutter/widgets.dart';
import '../../l10n/app_localizations.dart';

/// 仅转换运维界面字段与状态，机器数据和原始输出保持原样。
String maintenanceLabel(BuildContext context, String label) {
  final l10n = AppLocalizations.of(context)!;
  label = switch (label) {
    'Label' || 'label' || 'Name' || 'DisplayName' => '名称',
    'Description' => '描述',
    'Running' => '运行中',
    'Stopped' => '未运行',
    'Paused' => '暂停',
    'LISTENING' => 'LISTEN',
    'SYN_RECEIVED' => 'SYN_RECV',
    'SYN_RCVD' => 'SYN_RECV',
    'FIN_WAIT_1' => 'FIN_WAIT1',
    'FIN_WAIT_2' => 'FIN_WAIT2',
    _ => label,
  };
  return switch (label) {
    "账户与健康" => l10n.maintenanceHealthTab,
    "日志管理" => l10n.maintenanceLogsTab,
    "GPU 管理" => l10n.maintenanceGpuTab,
    "提交内存" => l10n.maintenanceMetricCommittedMemory,
    "任务线程数" => l10n.maintenanceMetricTaskThreads,
    "已分配文件句柄" => l10n.maintenanceMetricFileAllocated,
    "空闲文件句柄" => l10n.maintenanceMetricFileUnused,
    "交换倾向" => l10n.maintenanceMetricSwapTendency,
    "监听队列上限" => l10n.maintenanceMetricListenLimit,
    "CPU 配额" => l10n.maintenanceMetricCpuQuota,
    "CPU 配额周期" => l10n.maintenanceMetricCpuPeriod,
    "内存上限" => l10n.maintenanceMetricMemoryLimit,
    "当前内存" => l10n.maintenanceMetricMemoryCurrent,
    "不设上限" => l10n.maintenanceMetricUnlimited,
    "活跃内存" => l10n.maintenanceMetricActiveMemory,
    "非活跃内存" => l10n.maintenanceMetricInactiveMemory,
    "匿名内存" => l10n.maintenanceMetricAnonymousMemory,
    "内核对象缓存" => l10n.maintenanceMetricSlabMemory,
    "映射内存" => l10n.maintenanceMetricMappedMemory,
    "共享内存" => l10n.maintenanceMetricSharedMemory,
    "待写回内存" => l10n.maintenanceMetricDirtyMemory,
    "写回中内存" => l10n.maintenanceMetricWritebackMemory,
    "GUID 分区表" => l10n.maintenanceMetricGuidScheme,
    "APFS 卷" => l10n.maintenanceMetricApfsVolume,
    "APFS 快照" => l10n.maintenanceMetricApfsSnapshot,
    "APFS 容器" => l10n.maintenanceMetricApfsContainer,
    "数值" => l10n.maintenanceMetricValue,
    "单位" => l10n.maintenanceMetricUnit,
    "累计读取次数" => l10n.maintenanceMetricTotalReads,
    "累计写入次数" => l10n.maintenanceMetricTotalWrites,
    "累计读取字节" => l10n.maintenanceMetricBytesReadTotal,
    "累计写入字节" => l10n.maintenanceMetricBytesWrittenTotal,
    "累计读取耗时" => l10n.maintenanceMetricReadTimeTotal,
    "累计写入耗时" => l10n.maintenanceMetricWriteTimeTotal,
    "资源" => l10n.maintenanceMetricResource,
    "范围" => l10n.maintenanceMetricScope,
    "10 秒平均" => l10n.maintenanceMetric10SecondAverage,
    "60 秒平均" => l10n.maintenanceMetric60SecondAverage,
    "300 秒平均" => l10n.maintenanceMetric300SecondAverage,
    "累计等待时间" => l10n.maintenanceMetricTotalStallTime,
    "页数" => l10n.maintenanceMetricPages,
    "次数" => l10n.maintenanceMetricCount,
    "页大小" => l10n.maintenanceMetricPageSize,
    "空闲内存比例" => l10n.maintenanceMetricFreeMemory,
    "已用 inode" => l10n.maintenanceMetricUsedInodes,
    "可用 inode" => l10n.maintenanceMetricFreeInodes,
    "inode 使用率" => l10n.maintenanceMetricInodeUsage,
    "挂载点" => l10n.maintenanceMetricMountPoint,
    "容量" => l10n.maintenanceMetricCapacity,
    "所属设备" => l10n.maintenanceMetricParentDeviceBus,
    "主次设备号" => l10n.maintenanceMetricMajorMinor,
    "可移除" => l10n.maintenanceMetricRemovable,
    "只读" => l10n.maintenanceMetricReadOnly,
    "成员与同步状态" => l10n.maintenanceMetricMembersAndSyncStatus,
    "链路" => l10n.maintenanceMetricLinkGateway,
    "内核接口" => l10n.maintenanceMetricKernelInterfaces,
    "可用工具" => l10n.maintenanceMetricAvailableTools,
    "macOS 原生命令" => l10n.maintenanceMetricMacosTools,
    "磁盘累计计数" => l10n.maintenanceMetricCumulativeDiskCounters,
    "可用内存包含可回收页，具体统计口径因系统而异。" =>
      l10n.maintenanceMetricAvailableMemoryIncludesReclaimablePagesAccountingVaries,
    "部分字段未识别或不可用，已显示可解析的指标。" =>
      l10n.maintenanceMetricSomeFieldsAreUnrecognizedOrUnavailableParsed,
    "部分任务" => l10n.maintenanceMetricSomeTasks,
    "全部任务" => l10n.maintenanceMetricAllTasks,
    "换入页数" => l10n.maintenanceMetricSwapInPages,
    "换出页数" => l10n.maintenanceMetricSwapOutPages,
    "分页读取" => l10n.maintenanceMetricPageInVolume,
    "分页写入" => l10n.maintenanceMetricPageOutVolume,
    "交换空间总量" => l10n.maintenanceMetricTotalSwap,
    "空闲交换空间" => l10n.maintenanceMetricFreeSwap,
    "进程上限" => l10n.maintenanceMetricProcessLimit,
    "文件上限" => l10n.maintenanceMetricFileLimit,
    "线程上限" => l10n.maintenanceMetricThreadLimit,
    "已连接" => l10n.maintenanceMetricConnected,
    "未连接" => l10n.maintenanceMetricDisconnected,
    "物理存储" => l10n.maintenanceMetricPhysicalStore,
    "内部物理磁盘" => l10n.maintenanceMetricInternalPhysicalDisk,
    "合成磁盘" => l10n.maintenanceMetricSynthesizedDisk,
    "磁盘映像" => l10n.maintenanceMetricDiskImage,
    "POSIX Shell" => l10n.maintenancePosixShell,
    "PowerShell" => l10n.maintenancePowerShell,
    "CMD" => l10n.maintenanceCmdShell,
    "Windows SCM" => l10n.maintenanceWindowsScm,
    "Windows 服务管理器" => l10n.maintenanceWindowsScm,
    "SWAP" => l10n.maintenanceSwapSpace,
    "UUID / ID" => l10n.maintenanceDeviceIdentity,
    "GPU UUID" => l10n.maintenanceGpuUuid,
    "Metal" => l10n.maintenanceGpuMetal,
    "NVIDIA SMI" => l10n.maintenanceGpuSourceNvidia,
    "DRM / sysfs" => l10n.maintenanceGpuSourceDrm,
    "system_profiler / IOAccelerator" => l10n.maintenanceGpuSourceApple,
    "WMI" => l10n.maintenanceGpuSourceWindows,
    "macOS" => l10n.maintenanceMacos,
    "健康" => l10n.maintenanceHealthy,
    "服务器运维中心" => l10n.maintenanceCenter,
    "服务器运维" => l10n.maintenanceEntry,
    "运行总览" => l10n.maintenanceOverview,
    "进程管理" => l10n.maintenanceProcesses,
    "系统服务" => l10n.maintenanceServices,
    "网络与诊断" => l10n.maintenanceNetworkDiagnostics,
    "系统与内核" => l10n.maintenanceSystemKernel,
    "处理器型号" => l10n.maintenanceProcessorModel,
    "系统负载 · 1 / 5 / 15 分钟" => l10n.maintenanceLoadIntervals,
    "资源压力 · CPU / 内存 / IO" => l10n.maintenancePressure,
    "文件系统容量 · KiB" => l10n.maintenanceFilesystemCapacity,
    "文件系统 inode" => l10n.maintenanceInodes,
    "交换空间" => l10n.maintenanceSwapSpace,
    "网卡链路与硬件" => l10n.maintenanceInterfaces,
    "温度传感器" => l10n.maintenanceSensors,
    "内存详情" => l10n.maintenanceMemoryDetails,
    "内存统计口径" => l10n.maintenanceMemoryBasis,
    "内存与分页性能计数器" => l10n.maintenanceMemoryCounters,
    "虚拟内存计数器" => l10n.maintenanceVmCounters,
    "开机启动状态" => l10n.maintenanceStartup,
    "系统定时器" => l10n.maintenanceTimers,
    "连接与监听端口" => l10n.maintenanceSockets,
    "地址与路由" => l10n.maintenanceRoutes,
    "DNS 配置" => l10n.maintenanceDns,
    "最近日志" => l10n.maintenanceLogs,
    "登录用户" => l10n.maintenanceUsers,
    "当前用户计划任务" => l10n.maintenanceCron,
    "防火墙规则" => l10n.maintenanceFirewall,
    "容器状态" => l10n.maintenanceContainers,
    "状态详情" => l10n.maintenanceStatusDetails,
    "启动命令" => l10n.maintenanceCommand,
    "可执行文件与工作目录" => l10n.maintenancePaths,
    "进程 IO 计数器" => l10n.maintenanceProcessIo,
    "资源限制" => l10n.maintenanceLimits,
    "控制组" => l10n.maintenanceCgroup,
    "打开的文件描述符" => l10n.maintenanceDescriptors,
    "环境能力" => l10n.maintenanceCapabilities,
    "块设备与 RAID" => l10n.maintenanceBlocks,
    "控制组资源限制 · 容器与主机视图可能不同" => l10n.maintenanceCgroupLimits,
    "内核资源参数" => l10n.maintenanceKernel,
    "网卡累计计数 · 字节、包、错误与丢包" => l10n.maintenanceNetworkCounters,
    "采集中" => l10n.maintenanceCollecting,
    "采集异常" => l10n.maintenanceCollectionError,
    "自动刷新" => l10n.maintenanceAutoRefresh,
    "手动刷新" => l10n.maintenanceManualRefresh,
    "正在识别目标系统" => l10n.maintenanceDetecting,
    "自动识别 Shell" => l10n.maintenanceAutoShell,
    "终端 Shell" => l10n.maintenanceShell,
    "自动刷新间隔" => l10n.maintenanceInterval,
    "等待首次采样" => l10n.maintenanceFirstSample,
    "暂停自动刷新" => l10n.maintenancePauseRefresh,
    "开启自动刷新（当前分区）" => l10n.maintenanceStartRefresh,
    "刷新当前分区" => l10n.maintenanceRefreshSection,
    "当前终端 · 辅助命令不持久化 · 速率需两次采样" => l10n.maintenanceFooter,
    "正在连接当前终端" => l10n.maintenanceConnecting,
    "机器状态暂不可用" => l10n.maintenanceUnavailableHost,
    "识别系统并读取运行状态" => l10n.maintenanceIdentifying,
    "未能完成本次采集" => l10n.maintenanceCollectionFailed,
    "数据就绪后将显示资源、进程、服务与网络状态。" => l10n.maintenanceLoadingHelp,
    "请确认终端已连接并处于命令提示符，再重新采集。" => l10n.maintenanceRetryHelp,
    "重新采集" => l10n.maintenanceRetry,
    "内存" => l10n.maintenanceMemory,
    "磁盘" => l10n.maintenanceDisk,
    "网络" => l10n.maintenanceNetwork,
    "等待目标机器数据" => l10n.maintenanceWaitingData,
    "当前采样 · 完整原始内容" => l10n.maintenanceRawSample,
    "资源使用" => l10n.maintenanceResourceUse,
    "运行时间" => l10n.maintenanceUptime,
    "负载均衡" => l10n.maintenanceLoad,
    "处理器" => l10n.maintenanceProcessor,
    "采样状态" => l10n.maintenanceSampleStatus,
    "数据可能过期" => l10n.maintenanceStale,
    "采集成功" => l10n.maintenanceCollected,
    "刷新方式" => l10n.maintenanceRefreshMode,
    "趋势样本" => l10n.maintenanceTrendSamples,
    "目标平台" => l10n.maintenanceTargetPlatform,
    "速率根据连续采样计算；不可用字段不作推断。" => l10n.maintenanceRateHelp,
    "每核负载" => l10n.maintenancePerCore,
    "基本信息" => l10n.maintenanceBasicInfo,
    "系统原始信息" => l10n.maintenanceRawSystem,
    "主机名" => l10n.maintenanceHost,
    "操作系统" => l10n.maintenanceOs,
    "系统版本" => l10n.maintenanceOsVersion,
    "内核版本" => l10n.maintenanceKernelVersion,
    "逻辑处理器" => l10n.maintenanceLogicalCpus,
    "存储空间" => l10n.maintenanceStorage,
    "文件系统" => l10n.maintenanceFilesystem,
    "暂无可读的文件系统" => l10n.maintenanceNoFilesystem,
    "网络吞吐" => l10n.maintenanceThroughput,
    "网卡详情" => l10n.maintenanceInterfaceDetails,
    "网卡" => l10n.maintenanceInterface,
    "接收 / 秒" => l10n.maintenanceReceiveRate,
    "发送 / 秒" => l10n.maintenanceSendRate,
    "CPU 实时趋势" => l10n.maintenanceCpuTrend,
    "正在积累样本…" => l10n.maintenanceAccumulating,
    "开启自动刷新后显示趋势" => l10n.maintenanceTrendHelp,
    "运维操作" => l10n.maintenanceOperations,
    "查看进程" => l10n.maintenanceViewProcesses,
    "管理系统服务" => l10n.maintenanceManageServices,
    "网络诊断" => l10n.maintenanceNetworkAction,
    "资源提醒" => l10n.maintenanceAlerts,
    "暂无阈值提醒" => l10n.maintenanceNoAlerts,
    "依据当前 CPU 与内存采样，提醒阈值 85%；磁盘完整信息可在详情查看。" => l10n.maintenanceAlertHelp,
    "CPU 使用率" => l10n.maintenanceCpuUsage,
    "内存使用率" => l10n.maintenanceMemoryUsage,
    "暂无数据" => l10n.maintenanceNoData,
    "SWAP 使用量" => l10n.maintenanceSwapUsage,
    "未配置交换空间" => l10n.maintenanceNoSwap,
    "更多系统指标" => l10n.maintenanceMoreMetrics,
    "磁盘 IO" => l10n.maintenanceDiskIo,
    "设备" => l10n.maintenanceDevice,
    "读取 / 秒" => l10n.maintenanceReadRate,
    "写入 / 秒" => l10n.maintenanceWriteRate,
    "读 IOPS" => l10n.maintenanceReadIops,
    "写 IOPS" => l10n.maintenanceWriteIops,
    "当前环境未提供可用计数器。" => l10n.maintenanceNoCounters,
    "搜索 PID 或进程名" => l10n.maintenanceSearchProcess,
    "CPU 降序" => l10n.maintenanceSortCpu,
    "内存降序" => l10n.maintenanceSortMemory,
    "PID 升序" => l10n.maintenanceSortPid,
    "进程" => l10n.maintenanceProcess,
    "状态" => l10n.maintenanceStatus,
    "CPU / 单核" => l10n.maintenanceCpuPerCore,
    "驻留内存" => l10n.maintenanceResidentMemory,
    "线程" => l10n.maintenanceThreads,
    "不可用" => l10n.maintenanceUnavailable,
    "上一批进程" => l10n.maintenancePreviousBatch,
    "下一批进程" => l10n.maintenanceNextBatch,
    "运行中" => l10n.maintenanceRunning,
    "未运行" => l10n.maintenanceStopped,
    "未知" => l10n.maintenanceUnknown,
    "异常" => l10n.maintenanceFailed,
    "待检查" => l10n.maintenanceUnchecked,
    "已发现服务" => l10n.maintenanceDiscoveredServices,
    "当前可见服务" => l10n.maintenanceVisibleServices,
    "异常服务" => l10n.maintenanceFailedServices,
    "仅统计明确报告失败的条目" => l10n.maintenanceFailedServiceHelp,
    "筛选服务" => l10n.maintenanceSearchService,
    "未解析到 TCP / UDP 连接，可查看原始数据。" => l10n.maintenanceNoConnections,
    "协议" => l10n.maintenanceProtocol,
    "本地地址" => l10n.maintenanceLocalAddress,
    "远端地址" => l10n.maintenanceRemoteAddress,
    "DNS 服务器" => l10n.maintenanceDnsServers,
    "暂无可解析的服务器地址" => l10n.maintenanceNoDns,
    "诊断项目" => l10n.maintenanceDiagnosticItems,
    "已解析连接" => l10n.maintenanceParsedConnections,
    "当前采样中的 TCP / UDP" => l10n.maintenanceConnectionHelp,
    "解析自当前系统配置" => l10n.maintenanceDnsHelp,
    "路由、日志、任务与安全" => l10n.maintenanceDiagnosticHelp,
    "未提供" => l10n.maintenanceNotProvided,
    "运行" => l10n.maintenanceProcessRunning,
    "休眠" => l10n.maintenanceSleeping,
    "空闲" => l10n.maintenanceIdle,
    "暂停" => l10n.maintenanceSuspended,
    "僵尸" => l10n.maintenanceZombie,
    "IO 等待" => l10n.maintenanceIoWait,
    "部分不可用 · 查看原因" => l10n.maintenancePartial,
    "已采集 · 查看详情" => l10n.maintenanceViewCollected,
    "暂无可用数据" => l10n.maintenanceNoAvailableData,
    "查看详情" => l10n.maintenanceViewDetails,
    "确认执行" => l10n.maintenanceConfirm,
    "实时详情 · 部分字段需要更高权限" => l10n.maintenanceDetailSubtitle,
    "刷新详情" => l10n.maintenanceRefreshDetails,
    "正在读取详情…" => l10n.maintenanceLoadingDetails,
    "读取失败，请重试。" => l10n.maintenanceDetailsFailed,
    "终止进程" => l10n.maintenanceTerminate,
    "暂停进程" => l10n.maintenanceSuspend,
    "恢复进程" => l10n.maintenanceResume,
    "启动服务" => l10n.maintenanceStartService,
    "停止服务" => l10n.maintenanceStopService,
    "重启服务" => l10n.maintenanceRestartService,
    "启用开机启动" => l10n.maintenanceEnableStartup,
    "禁用开机启动" => l10n.maintenanceDisableStartup,
    "自动启动" => l10n.maintenanceAutomaticStartup,
    "手动启动" => l10n.maintenanceManualStartup,
    "禁用服务" => l10n.maintenanceDisableService,
    "所选 Shell 与目标系统不匹配，请改为自动识别或实际使用的 Shell。" => l10n.maintenanceShellMismatch,
    "ESTABLISHED" => l10n.maintenanceEstablished,
    "LISTEN" => l10n.maintenanceListening,
    "CLOSE_WAIT" => l10n.maintenanceCloseWait,
    "CLOSING" => l10n.maintenanceClosing,
    "TIME_WAIT" => l10n.maintenanceTimeWait,
    "SYN_SENT" => l10n.maintenanceSynSent,
    "SYN_RECV" => l10n.maintenanceSynReceived,
    "CLOSED" => l10n.maintenanceClosed,
    "LAST_ACK" => l10n.maintenanceLastAck,
    "FIN_WAIT1" => l10n.maintenanceFinWait1,
    "FIN_WAIT2" => l10n.maintenanceFinWait2,
    "UNCONN" => l10n.maintenanceUnconnected,
    "Start Pending" => l10n.maintenanceServiceStarting,
    "Stop Pending" => l10n.maintenanceServiceStopping,
    "ProductName" => l10n.maintenanceProductName,
    "ProductVersion" => l10n.maintenanceProductVersion,
    "BuildVersion" => l10n.maintenanceBuildVersion,
    "Routing tables" => l10n.maintenanceRoutingTables,
    "DNS configuration" => l10n.maintenanceDnsConfiguration,
    "Active Internet connections" => l10n.maintenanceActiveInternet,
    "Active Multipath Internet connections" => l10n.maintenanceActiveMultipath,
    "Active LOCAL (UNIX) domain sockets" => l10n.maintenanceActiveUnix,
    "nameserver" => l10n.maintenanceNameserver,
    "resolver" => l10n.maintenanceResolver,
    "if_index" => l10n.maintenanceIfIndex,
    "flags" => l10n.maintenanceFlags,
    "reach" => l10n.maintenanceReach,
    "本地化字段" => l10n.maintenanceLocalizedFields,
    "原始输出" => l10n.maintenanceOriginalOutput,
    "目的地址" => l10n.maintenanceDestination,
    "网关" => l10n.maintenanceGateway,
    "过期时间" => l10n.maintenanceExpires,
    "接收队列" => l10n.maintenanceReceiveQueue,
    "发送队列" => l10n.maintenanceSendQueue,
    "地址" => l10n.maintenanceAddress,
    "类型" => l10n.maintenanceType,
    "名称" => l10n.maintenanceName,
    "描述" => l10n.maintenanceDescription,
    "任务数" => l10n.maintenanceTaskCount,
    "重启次数" => l10n.maintenanceRestartCount,
    "已加载" => l10n.maintenanceLoaded,
    "已退出" => l10n.maintenanceExited,
    "静态" => l10n.maintenanceStatic,
    "已屏蔽" => l10n.maintenanceMasked,
    "累计 CPU 时间" => l10n.maintenanceCpuTime,
    "加载状态" => l10n.maintenanceLoadState,
    "子状态" => l10n.maintenanceSubState,
    "用户" => l10n.maintenanceDetailUser,
    "父进程 ID" => l10n.maintenanceParentPid,
    "用户 ID" => l10n.maintenanceUserId,
    "组 ID" => l10n.maintenanceGroupId,
    "优先级" => l10n.maintenancePriority,
    "虚拟内存" => l10n.maintenanceVirtualMemory,
    "启动方式" => l10n.maintenanceStartMode,
    "退出代码" => l10n.maintenanceExitCode,
    "路径" => l10n.maintenancePath,
    "架构" => l10n.maintenanceArchitecture,
    "加载地址" => l10n.maintenanceLoadAddress,
    "launchd" => l10n.maintenanceLaunchd,
    "充电状态" => l10n.maintenanceChargeState,
    "彩色液晶" => l10n.maintenanceColorLcd,
    "可用内存" => l10n.maintenanceAvailableMemory,
    "空闲内存" => l10n.maintenanceFreeMemory,
    "内存总量" => l10n.maintenanceTotalMemory,
    "缓存内存" => l10n.maintenanceCachedMemory,
    "缓冲区内存" => l10n.maintenanceBufferMemory,
    "读取字节" => l10n.maintenanceBytesRead,
    "写入字节" => l10n.maintenanceBytesWritten,
    "接收字节" => l10n.maintenanceReceiveBytes,
    "发送字节" => l10n.maintenanceSendBytes,
    _ => label,
  };
}

/// 只识别已知字段名和表头，不替换日志正文、地址、路径或其他值。
String maintenanceLocalizedOutput(BuildContext context, String output) {
  const fields = {
    'ProductName': 'ProductName',
    'ProductVersion': 'ProductVersion',
    'BuildVersion': 'BuildVersion',
    'nameserver': 'nameserver',
    'resolver': 'resolver',
    'if_index': 'if_index',
    'flags': 'flags',
    'reach': 'reach',
    'Name': '名称',
    'Caption': '名称',
    'Description': '描述',
    'State': '状态',
    'Status': '状态',
    'Threads': '线程',
    'ThreadCount': '线程',
    'PPid': '父进程 ID',
    'ParentProcessId': '父进程 ID',
    'Uid': '用户 ID',
    'Gid': '组 ID',
    'Priority': '优先级',
    'VmRSS': '驻留内存',
    'WorkingSetSize': '驻留内存',
    'VmSize': '虚拟内存',
    'VirtualSize': '虚拟内存',
    'StartMode': '启动方式',
    'ExitCode': '退出代码',
    'PathName': '路径',
    'ExecutablePath': '路径',
    'CommandLine': '启动命令',
    'OSArchitecture': '架构',
    'MemTotal': '内存总量',
    'MemFree': '空闲内存',
    'MemAvailable': '可用内存',
    'Cached': '缓存内存',
    'Buffers': '缓冲区内存',
    'read_bytes': '读取字节',
    'write_bytes': '写入字节',
    'rchar': '读取字节',
    'wchar': '写入字节',
  };
  const headings = {
    'Destination': '目的地址',
    'Gateway': '网关',
    'Flags': 'flags',
    'Netif': '网卡',
    'Iface': '网卡',
    'Expire': '过期时间',
    'Proto': '协议',
    'Proto/ID': '协议',
    'Recv-Q': '接收队列',
    'Send-Q': '发送队列',
    'Local Address': '本地地址',
    'Foreign Address': '远端地址',
    '(state)': '状态',
    'Address': '地址',
    'Type': '类型',
  };
  return output
      .split('\n')
      .map((line) {
        final trimmed = line.trim();
        if (const [
          'Routing tables',
          'DNS configuration',
          'Active Internet connections',
          'Active Multipath Internet connections',
          'Active LOCAL (UNIX) domain sockets',
        ].contains(trimmed)) {
          return maintenanceLabel(context, trimmed);
        }
        final field = RegExp(
          r'^(\s*)([A-Za-z_]+)(\[\d+\]| #\d+)?(\s*[:=].*|\s*)$',
        ).firstMatch(line);
        if (field != null && fields.containsKey(field[2])) {
          return '${field[1]}${maintenanceLabel(context, fields[field[2]]!)}${field[3] ?? ''}${field[4]}';
        }
        if (RegExp(
          r'^\s*(Destination\s+Gateway|Proto(?:/ID)?\s+|Address\s+Type)',
        ).hasMatch(line)) {
          for (final entry in headings.entries) {
            line = line.replaceAllMapped(
              RegExp('(?<![A-Za-z])${RegExp.escape(entry.key)}(?![A-Za-z])'),
              (_) => maintenanceLabel(context, entry.value),
            );
          }
        }
        return line;
      })
      .join('\n');
}

/// 仅本地化字段和枚举，保留设备标识、地址与测量值。
String maintenanceMetricLabel(
  BuildContext context,
  String value,
  String header, {
  String? section,
}) {
  if (!const ['名称', '类型', '状态', '资源', '范围', '单位', '数值'].contains(header)) {
    return value;
  }
  const fields = {
    'kern.num_taskthreads': '任务线程数',
    '/proc/sys/vm/swappiness': '交换倾向',
    '/proc/sys/net/core/somaxconn': '监听队列上限',
    'Active': '活跃内存',
    'Inactive': '非活跃内存',
    'AnonPages': '匿名内存',
    'Slab': '内核对象缓存',
    'Mapped': '映射内存',
    'Shmem': '共享内存',
    'Dirty': '待写回内存',
    'Writeback': '写回中内存',
    'Committed_AS': '提交内存',
    'GUID_partition_scheme': 'GUID 分区表',
    'APFS Volume': 'APFS 卷',
    'APFS Snapshot': 'APFS 快照',
    'APFS Container Scheme': 'APFS 容器',
    'Apple_APFS': 'APFS 容器',
    'max': '不设上限',
    'MemTotal': '内存总量',
    'MemFree': '空闲内存',
    'MemAvailable': '可用内存',
    'Cached': '缓存内存',
    'Buffers': '缓冲区内存',
    'SwapTotal': '交换空间总量',
    'SwapFree': '空闲交换空间',
    'nr_free_pages': '空闲内存',
    'nr_anon_pages': '匿名内存',
    'nr_file_pages': '缓存内存',
    'nr_shmem': '共享内存',
    'nr_mapped': '映射内存',
    'nr_dirty': '待写回内存',
    'nr_writeback': '写回中内存',
    'pgpgin': '分页读取',
    'pgpgout': '分页写入',
    'pswpin': '换入页数',
    'pswpout': '换出页数',
    'kern.osrelease': '内核版本',
    'kern.maxproc': '进程上限',
    'kern.maxfiles': '文件上限',
    '/proc/sys/kernel/pid_max': '进程上限',
    '/proc/sys/kernel/threads-max': '线程上限',
    '/proc/sys/fs/file-max': '文件上限',
    'AvailableBytes': '可用内存',
    'AvailableKBytes': '可用内存',
    'AvailableMBytes': '可用内存',
    'CommittedBytes': '提交内存',
    'cpu': 'CPU',
    'memory': '内存',
    'io': 'IO',
    'some': '部分任务',
    'full': '全部任务',
    'up': '已连接',
    'active': '已连接',
    'down': '未连接',
    'inactive': '未连接',
    'Physical Store': '物理存储',
    'internal, physical': '内部物理磁盘',
    'synthesized': '合成磁盘',
    'disk image': '磁盘映像',
  };
  if (header == '名称') {
    final counter = _maintenanceCounterLabel(
      AppLocalizations.of(context)!,
      value,
    );
    if (counter != null) return counter;
  }
  final translated = maintenanceLabel(context, fields[value] ?? value);
  if (header == '名称' &&
      translated == value &&
      RegExp('^[A-Za-z_/]').hasMatch(value) &&
      const [
        'memory',
        'memory_details',
        'vm',
        'kernel',
        'sensors',
      ].contains(section)) {
    return AppLocalizations.of(context)!.maintenanceExtendedMetric(value);
  }
  return translated;
}

/// 先匹配完整指标，再组合已知区域与回收方式；不翻译任意机器数据。
String? _maintenanceCounterLabel(
  AppLocalizations l10n,
  String name, {
  int depth = 0,
}) {
  if (depth > 4) return null;
  final exact = switch (name) {
    'pgalloc' => l10n.maintenanceCounterPgalloc,
    'pgfree' => l10n.maintenanceCounterPgfree,
    'pgactivate' => l10n.maintenanceCounterPgactivate,
    'pgdeactivate' => l10n.maintenanceCounterPgdeactivate,
    'pgfault' => l10n.maintenanceCounterPgfault,
    'PageFaultsPersec' => '${l10n.maintenanceCounterPgfault}/s',
    'pgmajfault' => l10n.maintenanceCounterPgmajfault,
    'pglazyfree' => l10n.maintenanceCounterPglazyfree,
    'pglazyfreed' => l10n.maintenanceCounterPglazyfreed,
    'pgrefill' => l10n.maintenanceCounterPgrefill,
    'pgsteal' => l10n.maintenanceCounterPgsteal,
    'pgscan' => l10n.maintenanceCounterPgscan,
    'allocstall' => l10n.maintenanceCounterAllocstall,
    'pgskip' => l10n.maintenanceCounterPgskip,
    'pgrotated' => l10n.maintenanceCounterPgrotated,
    'pginodesteal' => l10n.maintenanceCounterPginodesteal,
    'slabs_scanned' => l10n.maintenanceCounterSlabsScanned,
    'kswapd_inodesteal' => l10n.maintenanceCounterKswapdInodesteal,
    'kswapd_low_wmark_hit_quickly' =>
      l10n.maintenanceCounterKswapdLowWmarkHitQuickly,
    'kswapd_high_wmark_hit_quickly' =>
      l10n.maintenanceCounterKswapdHighWmarkHitQuickly,
    'pageoutrun' => l10n.maintenanceCounterPageoutrun,
    'pgmigrate_success' => l10n.maintenanceCounterPgmigrateSuccess,
    'pgmigrate_fail' => l10n.maintenanceCounterPgmigrateFail,
    'compact_stall' => l10n.maintenanceCounterCompactStall,
    'compact_fail' => l10n.maintenanceCounterCompactFail,
    'compact_success' => l10n.maintenanceCounterCompactSuccess,
    'compact_migrate_scanned' => l10n.maintenanceCounterCompactMigrateScanned,
    'compact_free_scanned' => l10n.maintenanceCounterCompactFreeScanned,
    'compact_isolated' => l10n.maintenanceCounterCompactIsolated,
    'unevictable' => l10n.maintenanceCounterUnevictable,
    'mlocked' => l10n.maintenanceCounterMlocked,
    'anon' => l10n.maintenanceCounterAnon,
    'file' => l10n.maintenanceCounterFile,
    'active' => l10n.maintenanceCounterActive,
    'inactive' => l10n.maintenanceCounterInactive,
    'isolated' => l10n.maintenanceCounterIsolated,
    'slab_reclaimable' ||
    'SReclaimable' => l10n.maintenanceCounterSlabReclaimable,
    'slab_unreclaimable' ||
    'SUnreclaim' => l10n.maintenanceCounterSlabUnreclaimable,
    'kernel_stack' || 'KernelStack' => l10n.maintenanceCounterKernelStack,
    'page_table_pages' || 'PageTables' => l10n.maintenanceCounterPageTablePages,
    'bounce' || 'Bounce' => l10n.maintenanceCounterBounce,
    'writeback_temp' || 'WritebackTmp' => l10n.maintenanceCounterWritebackTemp,
    'writeback' => l10n.maintenanceCounterWriteback,
    'dirtied' => l10n.maintenanceCounterDirtied,
    'written' => l10n.maintenanceCounterWritten,
    'dirty_threshold' => l10n.maintenanceCounterDirtyThreshold,
    'dirty_background_threshold' =>
      l10n.maintenanceCounterDirtyBackgroundThreshold,
    'numa_hit' => l10n.maintenanceCounterNumaHit,
    'numa_miss' => l10n.maintenanceCounterNumaMiss,
    'numa_foreign' => l10n.maintenanceCounterNumaForeign,
    'numa_interleave' => l10n.maintenanceCounterNumaInterleave,
    'numa_local' => l10n.maintenanceCounterNumaLocal,
    'numa_other' => l10n.maintenanceCounterNumaOther,
    'normal' => l10n.maintenanceCounterNormal,
    'movable' => l10n.maintenanceCounterMovable,
    'high' => l10n.maintenanceCounterHigh,
    'kswapd' => l10n.maintenanceCounterKswapd,
    'direct' => l10n.maintenanceCounterDirect,
    'throttle' => l10n.maintenanceCounterThrottle,
    'SwapCached' => l10n.maintenanceCounterSwapcached,
    'CommitLimit' => l10n.maintenanceCounterCommitlimit,
    'VmallocTotal' => l10n.maintenanceCounterVmalloctotal,
    'VmallocUsed' => l10n.maintenanceCounterVmallocused,
    'VmallocChunk' => l10n.maintenanceCounterVmallocchunk,
    'AnonHugePages' => l10n.maintenanceCounterAnonhugepages,
    'ShmemHugePages' => l10n.maintenanceCounterShmemhugepages,
    'ShmemPmdMapped' => l10n.maintenanceCounterShmempmdmapped,
    'HugePages_Total' => l10n.maintenanceCounterHugepagesTotal,
    'HugePages_Free' => l10n.maintenanceCounterHugepagesFree,
    'HugePages_Rsvd' => l10n.maintenanceCounterHugepagesRsvd,
    'HugePages_Surp' => l10n.maintenanceCounterHugepagesSurp,
    'Hugepagesize' => l10n.maintenanceCounterHugepagesize,
    'Hugetlb' => l10n.maintenanceCounterHugetlb,
    'Percpu' => l10n.maintenanceCounterPercpu,
    'HardwareCorrupted' => l10n.maintenanceCounterHardwarecorrupted,
    'KReclaimable' => l10n.maintenanceCounterKreclaimable,
    'NFS_Unstable' => l10n.maintenanceCounterNfsUnstable,
    'Mlocked' => l10n.maintenanceCounterMlocked,
    'Unevictable' => l10n.maintenanceCounterUnevictable,
    'workingset_refault' => l10n.maintenanceCounterWorkingsetRefault,
    'workingset_activate' => l10n.maintenanceCounterWorkingsetActivate,
    'workingset_restore' => l10n.maintenanceCounterWorkingsetRestore,
    'workingset_nodereclaim' => l10n.maintenanceCounterWorkingsetNodereclaim,
    'thp_fault_alloc' => l10n.maintenanceCounterThpFaultAlloc,
    'thp_fault_fallback' => l10n.maintenanceCounterThpFaultFallback,
    'thp_collapse_alloc' => l10n.maintenanceCounterThpCollapseAlloc,
    'thp_collapse_alloc_failed' =>
      l10n.maintenanceCounterThpCollapseAllocFailed,
    'thp_split_page' => l10n.maintenanceCounterThpSplitPage,
    'thp_split_page_failed' => l10n.maintenanceCounterThpSplitPageFailed,
    'thp_split_pmd' => l10n.maintenanceCounterThpSplitPmd,
    'thp_zero_page_alloc' => l10n.maintenanceCounterThpZeroPageAlloc,
    'thp_zero_page_alloc_failed' =>
      l10n.maintenanceCounterThpZeroPageAllocFailed,
    'thp_deferred_split_page' => l10n.maintenanceCounterThpDeferredSplitPage,
    'thp_swpout' => l10n.maintenanceCounterThpSwpout,
    'thp_swpout_fallback' => l10n.maintenanceCounterThpSwpoutFallback,
    'unevictable_pgs_culled' => l10n.maintenanceCounterUnevictablePgsCulled,
    'unevictable_pgs_scanned' => l10n.maintenanceCounterUnevictablePgsScanned,
    'unevictable_pgs_rescued' => l10n.maintenanceCounterUnevictablePgsRescued,
    'unevictable_pgs_mlocked' => l10n.maintenanceCounterUnevictablePgsMlocked,
    'unevictable_pgs_munlocked' =>
      l10n.maintenanceCounterUnevictablePgsMunlocked,
    'unevictable_pgs_cleared' => l10n.maintenanceCounterUnevictablePgsCleared,
    'unevictable_pgs_stranded' => l10n.maintenanceCounterUnevictablePgsStranded,
    'oom_kill' => l10n.maintenanceCounterOomKill,
    'numa_pte_updates' => l10n.maintenanceCounterNumaPteUpdates,
    'numa_huge_pte_updates' => l10n.maintenanceCounterNumaHugePteUpdates,
    'numa_hint_faults' => l10n.maintenanceCounterNumaHintFaults,
    'numa_hint_faults_local' => l10n.maintenanceCounterNumaHintFaultsLocal,
    'numa_pages_migrated' => l10n.maintenanceCounterNumaPagesMigrated,
    'compact_daemon_wake' => l10n.maintenanceCounterCompactDaemonWake,
    'compact_daemon_migrate_scanned' =>
      l10n.maintenanceCounterCompactDaemonMigrateScanned,
    'compact_daemon_free_scanned' =>
      l10n.maintenanceCounterCompactDaemonFreeScanned,
    'vmscan_write' => l10n.maintenanceCounterVmscanWrite,
    'vmscan_immediate_reclaim' => l10n.maintenanceCounterVmscanImmediateReclaim,
    'foll_pin_acquired' => l10n.maintenanceCounterFollPinAcquired,
    'foll_pin_released' => l10n.maintenanceCounterFollPinReleased,
    'anon_transparent_hugepages' =>
      l10n.maintenanceCounterAnonTransparentHugepages,
    'shmem_hugepages' => l10n.maintenanceCounterShmemHugepages,
    'shmem_pmdmapped' => l10n.maintenanceCounterShmemPmdmapped,
    'file_hugepages' || 'FileHugePages' => l10n.maintenanceCounterFileHugepages,
    'file_pmdmapped' || 'FilePmdMapped' => l10n.maintenanceCounterFilePmdmapped,
    'free_cma' || 'CmaFree' => l10n.maintenanceCounterFreeCma,
    'CmaTotal' => l10n.maintenanceCounterCmatotal,
    'PageReadsPersec' => l10n.maintenanceCounterPagereadspersec,
    'PageWritesPersec' => l10n.maintenanceCounterPagewritespersec,
    'PagesInputPersec' => l10n.maintenanceCounterPagesinputpersec,
    'PagesOutputPersec' => l10n.maintenanceCounterPagesoutputpersec,
    'PagesPersec' => l10n.maintenanceCounterPagespersec,
    'PoolPagedBytes' => l10n.maintenanceCounterPoolpagedbytes,
    'PoolNonpagedBytes' => l10n.maintenanceCounterPoolnonpagedbytes,
    'CacheBytes' => l10n.maintenanceCounterCachebytes,
    'PercentCommittedBytesInUse' =>
      l10n.maintenanceCounterPercentcommittedbytesinuse,
    'SystemCodeTotalBytes' => l10n.maintenanceCounterSystemcodetotalbytes,
    'SystemDriverTotalBytes' => l10n.maintenanceCounterSystemdrivertotalbytes,
    'anon_pages' => l10n.maintenanceCounterAnon,
    'file_pages' => l10n.maintenanceCounterFile,
    'free_pages' =>
      '${l10n.maintenanceFreeMemory} · ${l10n.maintenanceMetricPages}',
    'dma' => 'DMA',
    'dma32' => 'DMA32',
    _ => null,
  };
  if (exact != null) return exact;
  for (final suffix in const [
    '_dma32',
    '_dma',
    '_normal',
    '_movable',
    '_high',
    '_kswapd',
    '_direct',
    '_throttle',
    '_anon',
    '_file',
  ]) {
    if (!name.endsWith(suffix)) continue;
    final base = _maintenanceCounterLabel(
      l10n,
      name.substring(0, name.length - suffix.length),
      depth: depth + 1,
    );
    final qualifier = _maintenanceCounterLabel(l10n, suffix.substring(1));
    if (base != null && qualifier != null) return '$base · $qualifier';
  }
  final category = RegExp(
    r'^(Active|Inactive)\((anon|file)\)$',
  ).firstMatch(name);
  if (category != null) {
    return '${_maintenanceCounterLabel(l10n, category[1]!.toLowerCase())} · ${_maintenanceCounterLabel(l10n, category[2]!)}';
  }
  if (name.startsWith('nr_')) {
    return _maintenanceCounterLabel(l10n, name.substring(3), depth: depth + 1);
  }
  return null;
}

String maintenanceDetailLabel(BuildContext context, String field) {
  final l10n = AppLocalizations.of(context)!;
  const aliases = {
    'PPID': '父进程 ID',
    'USER': '用户',
    'STAT': '状态',
    'TYPE': '类型',
    'NI': '优先级',
    'PRI': '优先级',
    '%CPU': 'CPU / 单核',
    '%MEM': '内存使用率',
    'STARTED': '创建时间',
    'STATE': '状态',
    'UNIT FILE': '名称',
    'PRESET': '预设',
    'PID': 'PID',
    'RSS': '驻留内存',
    'VSZ': '虚拟内存',
    'TIME': '累计 CPU 时间',
    'ELAPSED': '运行时间',
    'CONTAINER ID': 'ID',
    'IMAGE': '镜像',
    'COMMAND': '启动命令',
    'FD': '打开的文件描述符',
    'NAME': '路径',
    'Process': '进程',
    'Path': '路径',
    'Parent Process': '父进程 ID',
    'Platform': '操作系统',
    'Code Type': '架构',
    'Version': '系统版本',
    'OS Version': '系统版本',
    'Identifier': 'UUID / ID',
    'Launch Time': '创建时间',
    'Date/Time': '时间',
    'Physical footprint': '驻留内存',
    'Physical footprint (peak)': '驻留内存',
    'Load Address': '加载地址',
    'Reason': '描述',
    'CREATED': '创建时间',
    'STATUS': '状态',
    'PORTS': '端口',
    'NAMES': '名称',
    'Limit': '资源限制',
    'Soft Limit': '软限制',
    'Hard Limit': '硬限制',
    'Units': '单位',
    'Name': '名称',
    'Label': '名称',
    'label': '名称',
    'DisplayName': '名称',
    'Program': '启动命令',
    'ProgramArguments': '启动命令',
    'WorkingDirectory': '工作目录',
    'UserName': '用户',
    'GroupName': '组',
    'LastExitStatus': '退出代码',
    'LoadState': '加载状态',
    'ExecMainStatus': '退出代码',
    'TasksCurrent': '任务数',
    'NRestarts': '重启次数',
    'MemoryCurrent': '内存',
    'Description': '描述',
    'State': '状态',
    'ActiveState': '状态',
    'SubState': '状态详情',
    'Restart': '重启策略',
    'NotifyAccess': '通知访问',
    'RestartUSec': '重启间隔',
    'TimeoutStartUSec': '启动超时',
    'TimeoutStopUSec': '停止超时',
    'WatchdogUSec': '监控超时',
    'Umask': '权限掩码',
    'TracerPid': '跟踪进程',
    'FDSize': '文件描述符上限',
    'Pid': 'PID',
    'MainPID': 'PID',
    'Tgid': 'PID',
    'PPid': '父进程 ID',
    'Uid': '用户 ID',
    'Gid': '组 ID',
    'Threads': '线程',
    'VmRSS': '驻留内存',
    'VmSize': '虚拟内存',
    'read_bytes': '读取字节',
    'write_bytes': '写入字节',
    'rchar': '读取字节',
    'wchar': '写入字节',
    'syscr': '累计读取次数',
    'syscw': '累计写入次数',
    'LogonId': 'ID',
    'LogonType': '类型',
    'StartTime': '登录时间',
    'UnitFileState': '启动方式',
    'ExecStart': '启动命令',
    'FragmentPath': '路径',
    'search': '域名搜索',
    'domain': '域名',
    'options': '选项',
  };
  final name = aliases[field] ?? field;
  final translated = switch (name) {
    '工作目录' => l10n.cronsWorkingDirectory,
    '组' => l10n.maintenanceAccountGroup,
    '系统代理' => l10n.maintenanceStartupSystemAgent,
    '用户代理' => l10n.maintenanceStartupUserAgent,
    '系统守护进程' => l10n.maintenanceStartupDaemon,
    '预设' => l10n.maintenanceStartupPreset,
    '间接启用' => l10n.maintenanceStartupIndirect,
    '自动生成' => l10n.maintenanceStartupGenerated,
    '临时' => l10n.maintenanceStartupTransient,
    '别名' => l10n.maintenanceStartupAlias,
    '已链接' => l10n.maintenanceStartupLinked,
    '临时启用' => l10n.maintenanceStartupEnabledRuntime,
    '临时屏蔽' => l10n.maintenanceStartupMaskedRuntime,
    '临时链接' => l10n.maintenanceStartupLinkedRuntime,

    '域名搜索' => l10n.maintenanceDetailSearchDomain,
    '域名' => l10n.maintenanceDetailDomain,
    '选项' => l10n.maintenanceDetailOptions,
    '用户' => l10n.maintenanceDetailUser,
    '终端' => l10n.maintenanceDetailTerminal,
    '登录时间' => l10n.maintenanceDetailLoginTime,
    '来源' => l10n.maintenanceDetailSource,
    '目标' => l10n.maintenanceDetailTarget,
    '权限' => l10n.maintenanceDetailPermissions,
    '计划' => l10n.maintenanceDetailSchedule,
    '时间' => l10n.maintenanceDetailTime,
    '消息' => l10n.maintenanceDetailMessage,
    '镜像' => l10n.maintenanceDetailImage,
    '创建时间' => l10n.maintenanceDetailCreated,
    '端口' => l10n.maintenanceDetailPorts,
    '重启策略' => l10n.maintenanceDetailRestartPolicy,
    '通知访问' => l10n.maintenanceDetailNotifyAccess,
    '重启间隔' => l10n.maintenanceDetailRestartDelay,
    '启动超时' => l10n.maintenanceDetailStartTimeout,
    '停止超时' => l10n.maintenanceDetailStopTimeout,
    '监控超时' => l10n.maintenanceDetailWatchdogTimeout,
    '权限掩码' => l10n.maintenanceDetailUmask,
    '跟踪进程' => l10n.maintenanceDetailTracer,
    '文件描述符上限' => l10n.maintenanceDetailDescriptorLimit,
    '软限制' => l10n.maintenanceDetailSoftLimit,
    '硬限制' => l10n.maintenanceDetailHardLimit,
    '启用' => l10n.maintenanceDetailEnabled,
    '禁用' => l10n.maintenanceDetailDisabled,
    '无' => l10n.maintenanceDetailNone,
    _ => maintenanceLabel(context, name),
  };
  if (translated != field ||
      !RegExp('^[A-Za-z_]').hasMatch(field) ||
      const ['ID', 'PID', 'MAC', 'MTU'].contains(field)) {
    return translated;
  }
  final legacy = maintenanceLocalizedOutput(context, '$field:');
  if (legacy != '$field:') return legacy.substring(0, legacy.length - 1);
  return l10n.maintenanceExtendedMetric(field);
}

const _englishMonths = <String, int>{
  'Jan': 1,
  'Feb': 2,
  'Mar': 3,
  'Apr': 4,
  'May': 5,
  'Jun': 6,
  'Jul': 7,
  'Aug': 8,
  'Sep': 9,
  'Oct': 10,
  'Nov': 11,
  'Dec': 12,
};

String? maintenanceEnglishTimestamp(String value) {
  final match = RegExp(
    r'^(?:(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun)\s+)?'
    r'(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+'
    r'(\d{1,2})\s+(\d{2}:\d{2}(?::\d{2})?)(?:\s+(\d{4}))?$',
  ).firstMatch(value.trim());
  if (match == null) return null;
  final month = _englishMonths[match[1]!]!;
  final day = int.parse(match[2]!);
  final year = int.parse(match[4] ?? '${DateTime.now().year}');
  return '${year.toString().padLeft(4, '0')}-'
      '${month.toString().padLeft(2, '0')}-'
      '${day.toString().padLeft(2, '0')} ${match[3]}';
}

String maintenanceDetailValue(BuildContext context, String value) {
  final l10n = AppLocalizations.of(context)!;
  final trimmed = value.trim();
  final metal = RegExp(r'^[Mm]etal\s*(\d+)$').firstMatch(trimmed);
  if (metal != null) return 'Metal ${metal[1]}';
  final stamp = maintenanceEnglishTimestamp(trimmed);
  if (stamp != null) return stamp;
  final lower = trimmed.toLowerCase();
  if (lower == 'darwin') return l10n.maintenanceMacos;
  if (lower == 'builtin' || lower == 'built-in') {
    return l10n.maintenanceBusBuiltin;
  }
  if (lower == 'launchd') return l10n.maintenanceLaunchd;
  if (lower == 'color lcd') return l10n.maintenanceColorLcd;
  final label = switch (trimmed) {
    'indirect' => '间接启用',
    'generated' => '自动生成',
    'transient' => '临时',
    'alias' => '别名',
    'linked' => '已链接',
    'enabled-runtime' => '临时启用',
    'masked-runtime' => '临时屏蔽',
    'linked-runtime' => '临时链接',
    'Auto' || 'Automatic' => '自动启动',
    'Manual' => '手动启动',
    'Disabled' => '禁用',
    'yes' || 'true' || 'enabled' => '启用',
    'no' || 'false' || 'disabled' => '禁用',
    'none' => '无',
    'loaded' => '已加载',
    'exited' => '已退出',
    'static' => '静态',
    'masked' => '已屏蔽',
    'active' || 'running' => '运行中',
    'inactive' || 'dead' => '未运行',
    'S (sleeping)' => '休眠',
    'R (running)' => '运行',
    'Z (zombie)' => '僵尸',
    _ => trimmed,
  };
  return label == trimmed && !const ['系统代理', '用户代理', '系统守护进程'].contains(trimmed)
      ? trimmed
      : maintenanceDetailLabel(context, label);
}

String maintenanceGpuFieldLabel(BuildContext context, String path) {
  final l10n = AppLocalizations.of(context)!;
  return path
      .split('/')
      .map((field) {
        final key = field.replaceAll(RegExp(r'\[\d+\]'), '');
        final label = switch (key) {
          'cuda_version' => l10n.maintenanceGpuCudaCompatibility,
          'gpu_fabric_info' => l10n.maintenanceGpuDetailFabric,
          'fb_memory_usage' => l10n.maintenanceGpuDetailMemory,
          'ecc_errors' => l10n.maintenanceGpuDetailEcc,
          'clocks_event_reasons' ||
          'clocks_throttle_reasons' => l10n.maintenanceGpuDetailThrottling,
          'utilization' => l10n.maintenanceGpuDetailUtilization,
          'NRestarts' => l10n.maintenanceGpuDetailRestarts,
          'LoadState' => l10n.maintenanceGpuDetailLoaded,
          'SubState' => l10n.maintenanceGpuDetailDetailState,
          'Result' => l10n.maintenanceGpuDetailResult,
          'attached_gpus' => l10n.maintenanceGpuDetailAttached,
          'driver_version' => l10n.maintenanceGpuDriver,
          'gpu_util' => l10n.maintenanceGpuUtil,
          'gpu_temp' || 'temperature' => l10n.maintenanceGpuTemperature,
          'power_draw' || 'power_readings' => l10n.maintenanceGpuPower,
          'power_limit' => l10n.maintenanceGpuPowerLimit,
          'processes' || 'process_info' => maintenanceLabel(context, '进程'),
          'product_name' || 'process_name' => maintenanceLabel(context, '名称'),
          'product_brand' => l10n.maintenanceGpuProductBrand,
          'product_architecture' => l10n.maintenanceHealthParsedArchitecture,
          'serial' ||
          'serial_number' ||
          'gpu_serial' => l10n.maintenanceGpuSerial,
          'uuid' || 'gpu_uuid' => l10n.maintenanceGpuUuid,
          'pci' || 'pci_bus' || 'bus_id' => l10n.maintenanceGpuBus,
          'fan_speed' => l10n.maintenanceGpuFan,
          'performance_state' ||
          'pstate' => l10n.maintenanceGpuPerformanceState,
          'vbios_version' => l10n.maintenanceGpuVbios,
          'board_id' => l10n.maintenanceGpuBoardId,
          'gpu_part_number' => l10n.maintenanceGpuPartNumber,
          'inforom_version' => l10n.maintenanceGpuInforom,
          'account_name' => l10n.maintenanceDetailUser,
          'used_gpu_memory' => l10n.maintenanceGpuMemoryUsed,
          'encoder_util' => l10n.maintenanceGpuEncoder,
          'decoder_util' => l10n.maintenanceGpuDecoder,
          'memory_util' => l10n.maintenanceGpuMemoryUtil,
          'gpu_busy_percent' => l10n.maintenanceGpuUtil,
          'version' => maintenanceHealthLabel(context, 'Version'),
          'path' => maintenanceLabel(context, '路径'),
          'state' ||
          'status' ||
          'ActiveState' => maintenanceLabel(context, '状态'),
          'pid' || 'MainPID' => 'PID',
          'MemoryCurrent' => '${maintenanceLabel(context, '内存')} (B)',
          'CPUUsageNSec' => l10n.maintenanceGpuDetailCpuTime,
          _ => l10n.maintenanceExtendedMetric(key),
        };
        return label + field.substring(key.length);
      })
      .join(' › ');
}

String maintenanceGpuSourceLabel(BuildContext context, String source) {
  return maintenanceLabel(context, source);
}

String maintenanceHealthLabel(BuildContext context, String field) {
  final l = AppLocalizations.of(context)!;
  return switch (field) {
    'GID' || 'ID' || 'UTC' || 'PID' => field,
    'Name' => maintenanceLabel(context, '名称'),

    "Architecture" => l.maintenanceHealthParsedArchitectureField,
    "Kernel" => l.maintenanceHealthParsedKernelName,
    "KernelRelease" => l.maintenanceHealthParsedKernelVersion,
    "Hostname" => l.maintenanceHealthParsedHostname,
    "present" => l.maintenanceHealthParsedBatteryPresent,
    "最少字符数" => l.maintenanceHealthParsedMinimumCharacters,
    "CycleCount" => l.maintenanceHealthParsedBatteryCycles,
    "DesignCapacity" => l.maintenanceHealthParsedDesignCapacityMAh,
    "Voltage" => l.maintenanceHealthParsedVoltageMV,
    "LogonId" => l.maintenanceHealthParsedLogonSessionID,
    "LogonType" => l.maintenanceHealthParsedLogonTypeCode,
    "StartTime" => l.maintenanceHealthParsedStartTime,
    "LastBootUpTime" => l.maintenanceHealthParsedLastBootTime,
    "Disabled" => l.maintenanceHealthParsedAccountDisabled,
    "Lockout" => l.maintenanceHealthParsedAccountLocked,
    "PasswordRequired" => l.maintenanceHealthParsedPasswordRequired,
    "PasswordExpires" => l.maintenanceHealthParsedPasswordExpires,
    "BatteryStatus" => l.maintenanceHealthParsedBatteryStatusCode,
    "EstimatedChargeRemaining" => l.maintenanceHealthParsedRemainingCharge,
    "EstimatedRunTime" => l.maintenanceHealthParsedEstimatedRuntimeMin,
    "LocalDateTime" => l.maintenanceHealthParsedLocalDateAndTime,
    "CurrentTimeZone" => l.maintenanceHealthParsedUTCOffsetMin,
    "StandardName" => l.maintenanceHealthParsedStandardTimeZone,
    "DaylightName" => l.maintenanceHealthParsedDaylightTimeZone,
    "Bias" => l.maintenanceHealthParsedUTCCorrectionMin,
    "Last password change" => l.maintenanceHealthParsedLastPasswordChange,
    "Password expires" => l.maintenanceHealthParsedPasswordExpiry,
    "Password inactive" => l.maintenanceHealthParsedPasswordInactivityDate,
    "Account expires" => l.maintenanceHealthParsedAccountExpiry,
    "Minimum number of days between password change" =>
      l.maintenanceHealthParsedMinimumPasswordAgeDays,
    "Maximum number of days between password change" =>
      l.maintenanceHealthParsedMaximumPasswordAgeDays,
    "Number of days of warning before password expires" =>
      l.maintenanceHealthParsedPasswordExpiryWarningDays,
    "Reference ID" => l.maintenanceHealthParsedReferenceClockID,
    "Ref time (UTC)" => l.maintenanceHealthParsedReferenceTimeUTC,
    "System time" => l.maintenanceHealthParsedSystemClockOffset,
    "Last offset" => l.maintenanceHealthParsedLastOffset,
    "RMS offset" => l.maintenanceHealthParsedRMSOffset,
    "Frequency" => l.maintenanceHealthParsedFrequencyError,
    "Residual freq" => l.maintenanceHealthParsedResidualFrequency,
    "Skew" => l.maintenanceHealthParsedFrequencySkew,
    "Root delay" => l.maintenanceHealthParsedRootDelay,
    "Root dispersion" => l.maintenanceHealthParsedRootDispersion,
    "Update interval" => l.maintenanceHealthParsedUpdateInterval,
    "Leap status" => l.maintenanceHealthParsedLeapStatus,
    "最近轮转" => l.maintenanceHealthParsedLastRotation,
    "保留份数" => l.maintenanceHealthParsedRetainedCopies,
    "大小阈值" => l.maintenanceHealthParsedSizeThreshold,
    "轮转时间" => l.maintenanceHealthParsedRotationSchedule,
    "daily" => l.maintenanceHealthParsedDailyRotation,
    "weekly" => l.maintenanceHealthParsedWeeklyRotation,
    "monthly" => l.maintenanceHealthParsedMonthlyRotation,
    "rotate" => l.maintenanceHealthParsedRetainedCopiesField,
    "compress" => l.maintenanceHealthParsedCompressArchives,
    "delaycompress" => l.maintenanceHealthParsedDelayCompression,
    "missingok" => l.maintenanceHealthParsedAllowMissingLogs,
    "notifempty" => l.maintenanceHealthParsedSkipEmptyLogs,
    "create" => l.maintenanceHealthParsedNewLogModeAndOwner,
    "postrotate" => l.maintenanceHealthParsedPostRotationScript,
    "sharedscripts" => l.maintenanceHealthParsedSharedRotationScripts,
    "include" => l.maintenanceHealthParsedIncludedRules,
    "size" => l.maintenanceHealthParsedSizeThresholdField,
    "usepam" => l.maintenanceHealthParsedPAMAuthentication,
    "allowusers" => l.maintenanceHealthParsedAllowedUsers,
    "denyusers" => l.maintenanceHealthParsedDeniedUsers,
    "allowgroups" => l.maintenanceHealthParsedAllowedGroups,
    "denygroups" => l.maintenanceHealthParsedDeniedGroups,
    "permission" =>
      l.maintenanceHealthParsedInsufficientPermissionsForThisAccount,
    "missing" => l.maintenanceHealthParsedCollectionToolIsMissingOrUnavailable,
    "hostkeys" =>
      l.maintenanceHealthParsedSSHConfigurationCheckFailedHostKeysUnavailable,
    "format" =>
      l.maintenanceHealthParsedUnrecognizedDataFormatInspectCollectionDetails,
    "pending" => l.maintenanceHealthParsedNotCollectedYet,
    "diagnostic" => l.maintenanceHealthParsedCollectionDetailsAndDiagnostics,
    "user" => l.maintenanceHealthParsedAccount,
    "home" => l.maintenanceHealthParsedHomeDirectory,
    "sensor" => l.maintenanceHealthParsedSensor,
    "登录时间" => l.maintenanceHealthParsedLoginTime,
    "空闲时间" => l.maintenanceHealthParsedIdleTime,
    "来源" => l.maintenanceHealthParsedSource,
    "本地时间" => l.maintenanceHealthParsedLocalTime,
    "时区" => l.maintenanceHealthParsedTimeZone,
    "架构" => l.maintenanceHealthParsedArchitecture,
    "ProductName" => l.maintenanceHealthParsedSystemName,
    "ProductVersion" => l.maintenanceHealthParsedSystemVersion,
    "BuildVersion" => l.maintenanceHealthParsedBuildVersion,
    "供电来源" => l.maintenanceHealthParsedPowerSource,
    "充电状态" => l.maintenanceChargeState,
    "电量" => l.maintenanceHealthParsedBatteryCharge,
    "温度告警" => l.maintenanceHealthParsedThermalWarning,
    "性能告警" => l.maintenanceHealthParsedPerformanceWarning,
    "CPU 电源状态" => l.maintenanceHealthParsedCPUPowerStatus,
    "policyIdentifier" => l.maintenanceHealthParsedPolicyIdentifier,
    "policyContent" => l.maintenanceHealthParsedPolicyExpression,
    "密码状态" => l.maintenanceHealthParsedPasswordStatus,
    "最近修改" => l.maintenanceHealthParsedLastChange,
    "最短使用天数" => l.maintenanceHealthParsedMinimumAgeDays,
    "最长使用天数" => l.maintenanceHealthParsedMaximumAgeDays,
    "到期预警天数" => l.maintenanceHealthParsedExpiryWarningDays,
    "失效天数" => l.maintenanceHealthParsedInactivityDays,
    "port" => l.maintenanceHealthParsedListeningPort,
    "listenaddress" => l.maintenanceHealthParsedListeningAddress,
    "permitrootlogin" => l.maintenanceHealthParsedRootLoginPolicy,
    "passwordauthentication" => l.maintenanceHealthParsedPasswordAuthentication,
    "pubkeyauthentication" => l.maintenanceHealthParsedPublicKeyAuthentication,
    "kbdinteractiveauthentication" =>
      l.maintenanceHealthParsedInteractiveAuthentication,
    "permitemptypasswords" => l.maintenanceHealthParsedAllowEmptyPasswords,
    "maxauthtries" => l.maintenanceHealthParsedMaximumAuthenticationAttempts,
    "maxsessions" => l.maintenanceHealthParsedMaximumSessions,
    "logingracetime" => l.maintenanceHealthParsedLoginGraceTimeS,
    "clientaliveinterval" => l.maintenanceHealthParsedKeepaliveIntervalS,
    "clientalivecountmax" => l.maintenanceHealthParsedMaximumMissedKeepalives,
    "authenticationmethods" => l.maintenanceHealthParsedAuthenticationMethods,
    "NTPSynchronized" => l.maintenanceHealthParsedClockSynchronized,
    "NTP" => l.maintenanceHealthParsedNetworkTimeEnabled,
    "LocalRTC" => l.maintenanceHealthParsedRTCUsesLocalTime,
    "Network Time" => l.maintenanceHealthParsedNetworkTime,
    "Network Time Server" => l.maintenanceHealthParsedTimeServer,
    "poll" => l.maintenanceHealthParsedPollingInterval,
    "reach" => l.maintenanceHealthParsedReachRegisterOctal,
    "stratum" => l.maintenanceHealthParsedStratum,
    "offset" => l.maintenanceHealthParsedClockOffset,
    "lastRx" => l.maintenanceHealthParsedLastReceived,
    "configured" =>
      l.maintenanceHealthParsedConfiguredValueDoesNotConfirmSynchronization,
    "uid" || "UID" => "UID",
    "celsius" => "°C",
    "shell" || "Shell" => "Shell",
    "PRETTY_NAME" => maintenanceHealthLabel(context, "ProductName"),
    "NAME" => maintenanceHealthLabel(context, "ProductName"),
    "Caption" => maintenanceHealthLabel(context, "ProductName"),
    "VERSION_ID" => maintenanceHealthLabel(context, "ProductVersion"),
    "Version" => maintenanceHealthLabel(context, "ProductVersion"),
    "BuildNumber" => maintenanceHealthLabel(context, "BuildVersion"),
    "OSArchitecture" => maintenanceHealthLabel(context, "架构"),
    "CSName" => maintenanceDetailLabel(context, "主机名"),
    "Timezone" => maintenanceHealthLabel(context, "时区"),
    "type" => maintenanceDetailLabel(context, "类型"),
    "status" => maintenanceDetailLabel(context, "状态"),
    "capacity" => maintenanceHealthLabel(context, "电量"),
    "Source" => maintenanceHealthLabel(context, "来源"),
    "Stratum" => maintenanceHealthLabel(context, "stratum"),
    _ => maintenanceDetailLabel(context, field),
  };
}

String maintenanceHealthValue(BuildContext context, String value) {
  final timestamp = RegExp(
    r'^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})\.\d{6}([+-])(\d{3})$',
  ).firstMatch(value);
  if (timestamp != null) {
    final offset = int.parse(timestamp[8]!);
    return '${timestamp[1]}-${timestamp[2]}-${timestamp[3]} ${timestamp[4]}:${timestamp[5]}:${timestamp[6]} UTC${timestamp[7]}${(offset ~/ 60).toString().padLeft(2, '0')}:${(offset % 60).toString().padLeft(2, '0')}';
  }
  final english = maintenanceEnglishTimestamp(value);
  if (english != null) return english;
  final l = AppLocalizations.of(context)!;
  final trimmed = value.trim();
  final logout = RegExp(
    r'^-\s+(\d{1,2}:\d{2}(?::\d{2})?)\s+\(([^)]+)\)$',
  ).firstMatch(trimmed);
  if (logout != null) return l.maintenanceExited;
  return switch (trimmed) {
    'Darwin' || 'darwin' => l.maintenanceMacos,
    'P' || 'PS' => l.maintenanceHealthParsedPasswordSet,
    'L' || 'LK' => l.maintenanceHealthParsedPasswordLocked,
    'NP' => l.maintenanceHealthParsedPasswordEmpty,
    'never' => l.maintenanceHealthParsedNever,
    '已配置' => l.maintenanceHealthParsedConfigured,

    "无告警记录" => l.maintenanceHealthParsedNoWarningRecorded,
    "未记录" => l.maintenanceHealthParsedNotRecorded,
    "AC Power" => l.maintenanceHealthParsedACPower,
    "Battery Power" => l.maintenanceHealthParsedBatteryPower,
    "AC attached" => l.maintenanceHealthParsedACConnected,
    "not charging" => l.maintenanceHealthParsedNotCharging,
    "charging" => l.maintenanceHealthParsedCharging,
    "discharging" => l.maintenanceHealthParsedDischarging,
    "charged" => l.maintenanceHealthParsedCharged,
    "still logged in" => l.maintenanceHealthParsedStillLoggedIn,
    "yes" => l.maintenanceHealthParsedYes,
    "no" => l.maintenanceHealthParsedNo,
    'true' || 'On' => l.maintenanceHealthParsedYes,
    'false' || 'Off' => l.maintenanceHealthParsedNo,
    _ => maintenanceDetailValue(context, value),
  };
}
