// 国家、地区与洲名称来自 Unicode CLDR 48.2；按英文、简中、繁中、德文、法文、日文排列。
// 来源：https://github.com/unicode-org/cldr-json/tree/48.2.0/cldr-json/cldr-localenames-full
// 授权见同目录 UNICODE-LICENSE.txt；仅包含界面所需的地理名称。
const machineEgressRegionNames = <String, List<String>>{
  "002": ["Africa", "非洲", "非洲", "Afrika", "Afrique", "アフリカ"],
  "003": [
    "North America",
    "北美洲",
    "北美洲",
    "Nordamerika",
    "Amérique du Nord",
    "北アメリカ大陸",
  ],
  "005": [
    "South America",
    "南美洲",
    "南美洲",
    "Südamerika",
    "Amérique du Sud",
    "南アメリカ",
  ],
  "009": ["Oceania", "大洋洲", "大洋洲", "Ozeanien", "Océanie", "オセアニア"],
  "142": ["Asia", "亚洲", "亞洲", "Asien", "Asie", "アジア"],
  "150": ["Europe", "欧洲", "歐洲", "Europa", "Europe", "ヨーロッパ"],
  "AC": [
    "Ascension Island",
    "阿森松岛",
    "阿森松島",
    "Ascension",
    "Île de l’Ascension",
    "アセンション島",
  ],
  "AD": ["Andorra", "安道尔", "安道爾", "Andorra", "Andorre", "アンドラ"],
  "AE": [
    "United Arab Emirates",
    "阿拉伯联合酋长国",
    "阿拉伯聯合大公國",
    "Vereinigte Arabische Emirate",
    "Émirats arabes unis",
    "アラブ首長国連邦",
  ],
  "AF": ["Afghanistan", "阿富汗", "阿富汗", "Afghanistan", "Afghanistan", "アフガニスタン"],
  "AG": [
    "Antigua & Barbuda",
    "安提瓜和巴布达",
    "安地卡及巴布達",
    "Antigua und Barbuda",
    "Antigua-et-Barbuda",
    "アンティグア・バーブーダ",
  ],
  "AI": ["Anguilla", "安圭拉", "安奎拉", "Anguilla", "Anguilla", "アンギラ"],
  "AL": ["Albania", "阿尔巴尼亚", "阿爾巴尼亞", "Albanien", "Albanie", "アルバニア"],
  "AM": ["Armenia", "亚美尼亚", "亞美尼亞", "Armenien", "Arménie", "アルメニア"],
  "AO": ["Angola", "安哥拉", "安哥拉", "Angola", "Angola", "アンゴラ"],
  "AQ": ["Antarctica", "南极洲", "南極洲", "Antarktis", "Antarctique", "南極"],
  "AR": ["Argentina", "阿根廷", "阿根廷", "Argentinien", "Argentine", "アルゼンチン"],
  "AS": [
    "American Samoa",
    "美属萨摩亚",
    "美屬薩摩亞",
    "Amerikanisch-Samoa",
    "Samoa américaines",
    "米領サモア",
  ],
  "AT": ["Austria", "奥地利", "奧地利", "Österreich", "Autriche", "オーストリア"],
  "AU": ["Australia", "澳大利亚", "澳洲", "Australien", "Australie", "オーストラリア"],
  "AW": ["Aruba", "阿鲁巴", "荷屬阿魯巴", "Aruba", "Aruba", "アルバ"],
  "AX": [
    "Åland Islands",
    "奥兰群岛",
    "奧蘭群島",
    "Ålandinseln",
    "Îles Åland",
    "オーランド諸島",
  ],
  "AZ": [
    "Azerbaijan",
    "阿塞拜疆",
    "亞塞拜然",
    "Aserbaidschan",
    "Azerbaïdjan",
    "アゼルバイジャン",
  ],
  "BA": [
    "Bosnia & Herzegovina",
    "波斯尼亚和黑塞哥维那",
    "波士尼亞與赫塞哥維納",
    "Bosnien und Herzegowina",
    "Bosnie-Herzégovine",
    "ボスニア・ヘルツェゴビナ",
  ],
  "BB": ["Barbados", "巴巴多斯", "巴貝多", "Barbados", "Barbade", "バルバドス"],
  "BD": ["Bangladesh", "孟加拉国", "孟加拉", "Bangladesch", "Bangladesh", "バングラデシュ"],
  "BE": ["Belgium", "比利时", "比利時", "Belgien", "Belgique", "ベルギー"],
  "BF": [
    "Burkina Faso",
    "布基纳法索",
    "布吉納法索",
    "Burkina Faso",
    "Burkina Faso",
    "ブルキナファソ",
  ],
  "BG": ["Bulgaria", "保加利亚", "保加利亞", "Bulgarien", "Bulgarie", "ブルガリア"],
  "BH": ["Bahrain", "巴林", "巴林", "Bahrain", "Bahreïn", "バーレーン"],
  "BI": ["Burundi", "布隆迪", "蒲隆地", "Burundi", "Burundi", "ブルンジ"],
  "BJ": ["Benin", "贝宁", "貝南", "Benin", "Bénin", "ベナン"],
  "BL": [
    "St. Barthélemy",
    "圣巴泰勒米",
    "聖巴瑟米",
    "St. Barthélemy",
    "Saint-Barthélemy",
    "サン・バルテルミー",
  ],
  "BM": ["Bermuda", "百慕大", "百慕達", "Bermuda", "Bermudes", "バミューダ"],
  "BN": ["Brunei", "文莱", "汶萊", "Brunei Darussalam", "Brunei", "ブルネイ"],
  "BO": ["Bolivia", "玻利维亚", "玻利維亞", "Bolivien", "Bolivie", "ボリビア"],
  "BQ": [
    "Caribbean Netherlands",
    "荷属加勒比区",
    "荷蘭加勒比區",
    "Karibische Niederlande",
    "Pays-Bas caribéens",
    "オランダ領カリブ",
  ],
  "BR": ["Brazil", "巴西", "巴西", "Brasilien", "Brésil", "ブラジル"],
  "BS": ["Bahamas", "巴哈马", "巴哈馬", "Bahamas", "Bahamas", "バハマ"],
  "BT": ["Bhutan", "不丹", "不丹", "Bhutan", "Bhoutan", "ブータン"],
  "BV": ["Bouvet Island", "布韦岛", "布威島", "Bouvetinsel", "Île Bouvet", "ブーベ島"],
  "BW": ["Botswana", "博茨瓦纳", "波札那", "Botsuana", "Botswana", "ボツワナ"],
  "BY": ["Belarus", "白俄罗斯", "白俄羅斯", "Belarus", "Biélorussie", "ベラルーシ"],
  "BZ": ["Belize", "伯利兹", "貝里斯", "Belize", "Belize", "ベリーズ"],
  "CA": ["Canada", "加拿大", "加拿大", "Kanada", "Canada", "カナダ"],
  "CC": [
    "Cocos (Keeling) Islands",
    "科科斯（基林）群岛",
    "科克斯（基靈）群島",
    "Kokosinseln",
    "Îles Cocos",
    "ココス(キーリング)諸島",
  ],
  "CD": [
    "Congo - Kinshasa",
    "刚果（金）",
    "剛果（金夏沙）",
    "Kongo-Kinshasa",
    "Congo-Kinshasa",
    "コンゴ民主共和国(キンシャサ)",
  ],
  "CF": [
    "Central African Republic",
    "中非共和国",
    "中非共和國",
    "Zentralafrikanische Republik",
    "République centrafricaine",
    "中央アフリカ共和国",
  ],
  "CG": [
    "Congo - Brazzaville",
    "刚果（布）",
    "剛果（布拉薩）",
    "Kongo-Brazzaville",
    "Congo-Brazzaville",
    "コンゴ共和国(ブラザビル)",
  ],
  "CH": ["Switzerland", "瑞士", "瑞士", "Schweiz", "Suisse", "スイス"],
  "CI": [
    "Côte d’Ivoire",
    "科特迪瓦",
    "象牙海岸",
    "Côte d’Ivoire",
    "Côte d’Ivoire",
    "コートジボワール",
  ],
  "CK": ["Cook Islands", "库克群岛", "庫克群島", "Cookinseln", "Îles Cook", "クック諸島"],
  "CL": ["Chile", "智利", "智利", "Chile", "Chili", "チリ"],
  "CM": ["Cameroon", "喀麦隆", "喀麥隆", "Kamerun", "Cameroun", "カメルーン"],
  "CN": ["China", "中国", "中國", "China", "Chine", "中国"],
  "CO": ["Colombia", "哥伦比亚", "哥倫比亞", "Kolumbien", "Colombie", "コロンビア"],
  "CP": [
    "Clipperton Island",
    "克利珀顿岛",
    "克里派頓島",
    "Clipperton-Insel",
    "Île Clipperton",
    "クリッパートン島",
  ],
  "CQ": ["Sark", "萨克岛", "薩克島", "Sark", "Sercq", "サーク島"],
  "CR": ["Costa Rica", "哥斯达黎加", "哥斯大黎加", "Costa Rica", "Costa Rica", "コスタリカ"],
  "CU": ["Cuba", "古巴", "古巴", "Kuba", "Cuba", "キューバ"],
  "CV": ["Cape Verde", "佛得角", "維德角", "Cabo Verde", "Cap-Vert", "カーボベルデ"],
  "CW": ["Curaçao", "库拉索", "庫拉索", "Curaçao", "Curaçao", "キュラソー"],
  "CX": [
    "Christmas Island",
    "圣诞岛",
    "聖誕島",
    "Weihnachtsinsel",
    "Île Christmas",
    "クリスマス島",
  ],
  "CY": ["Cyprus", "塞浦路斯", "賽普勒斯", "Zypern", "Chypre", "キプロス"],
  "CZ": ["Czechia", "捷克", "捷克", "Tschechien", "Tchéquie", "チェコ"],
  "DE": ["Germany", "德国", "德國", "Deutschland", "Allemagne", "ドイツ"],
  "DG": [
    "Diego Garcia",
    "迪戈加西亚岛",
    "迪亞哥加西亞島",
    "Diego Garcia",
    "Diego Garcia",
    "ディエゴガルシア島",
  ],
  "DJ": ["Djibouti", "吉布提", "吉布地", "Dschibuti", "Djibouti", "ジブチ"],
  "DK": ["Denmark", "丹麦", "丹麥", "Dänemark", "Danemark", "デンマーク"],
  "DM": ["Dominica", "多米尼克", "多米尼克", "Dominica", "Dominique", "ドミニカ国"],
  "DO": [
    "Dominican Republic",
    "多米尼加共和国",
    "多明尼加共和國",
    "Dominikanische Republik",
    "République dominicaine",
    "ドミニカ共和国",
  ],
  "DZ": ["Algeria", "阿尔及利亚", "阿爾及利亞", "Algerien", "Algérie", "アルジェリア"],
  "EA": [
    "Ceuta & Melilla",
    "休达及梅利利亚",
    "休達與梅利利亞",
    "Ceuta und Melilla",
    "Ceuta et Melilla",
    "セウタ・メリリャ",
  ],
  "EC": ["Ecuador", "厄瓜多尔", "厄瓜多", "Ecuador", "Équateur", "エクアドル"],
  "EE": ["Estonia", "爱沙尼亚", "愛沙尼亞", "Estland", "Estonie", "エストニア"],
  "EG": ["Egypt", "埃及", "埃及", "Ägypten", "Égypte", "エジプト"],
  "EH": [
    "Western Sahara",
    "西撒哈拉",
    "西撒哈拉",
    "Westsahara",
    "Sahara occidental",
    "西サハラ",
  ],
  "ER": ["Eritrea", "厄立特里亚", "厄利垂亞", "Eritrea", "Érythrée", "エリトリア"],
  "ES": ["Spain", "西班牙", "西班牙", "Spanien", "Espagne", "スペイン"],
  "ET": ["Ethiopia", "埃塞俄比亚", "衣索比亞", "Äthiopien", "Éthiopie", "エチオピア"],
  "EU": [
    "European Union",
    "欧盟",
    "歐盟",
    "Europäische Union",
    "Union européenne",
    "欧州連合",
  ],
  "EZ": ["Eurozone", "欧元区", "歐元區", "Eurozone", "zone euro", "ユーロ圏"],
  "FI": ["Finland", "芬兰", "芬蘭", "Finnland", "Finlande", "フィンランド"],
  "FJ": ["Fiji", "斐济", "斐濟", "Fidschi", "Fidji", "フィジー"],
  "FK": [
    "Falkland Islands",
    "福克兰群岛",
    "福克蘭群島",
    "Falklandinseln",
    "Îles Malouines",
    "フォークランド諸島",
  ],
  "FM": [
    "Micronesia",
    "密克罗尼西亚",
    "密克羅尼西亞",
    "Mikronesien",
    "Micronésie",
    "ミクロネシア連邦",
  ],
  "FO": ["Faroe Islands", "法罗群岛", "法羅群島", "Färöer", "Îles Féroé", "フェロー諸島"],
  "FR": ["France", "法国", "法國", "Frankreich", "France", "フランス"],
  "GA": ["Gabon", "加蓬", "加彭", "Gabun", "Gabon", "ガボン"],
  "GB": [
    "United Kingdom",
    "英国",
    "英國",
    "Vereinigtes Königreich",
    "Royaume-Uni",
    "イギリス",
  ],
  "GD": ["Grenada", "格林纳达", "格瑞那達", "Grenada", "Grenade", "グレナダ"],
  "GE": ["Georgia", "格鲁吉亚", "喬治亞", "Georgien", "Géorgie", "ジョージア"],
  "GF": [
    "French Guiana",
    "法属圭亚那",
    "法屬圭亞那",
    "Französisch-Guayana",
    "Guyane française",
    "仏領ギアナ",
  ],
  "GG": ["Guernsey", "根西岛", "根息", "Guernsey", "Guernesey", "ガーンジー"],
  "GH": ["Ghana", "加纳", "迦納", "Ghana", "Ghana", "ガーナ"],
  "GI": ["Gibraltar", "直布罗陀", "直布羅陀", "Gibraltar", "Gibraltar", "ジブラルタル"],
  "GL": ["Greenland", "格陵兰", "格陵蘭", "Grönland", "Groenland", "グリーンランド"],
  "GM": ["Gambia", "冈比亚", "甘比亞", "Gambia", "Gambie", "ガンビア"],
  "GN": ["Guinea", "几内亚", "幾內亞", "Guinea", "Guinée", "ギニア"],
  "GP": ["Guadeloupe", "瓜德罗普", "瓜地洛普", "Guadeloupe", "Guadeloupe", "グアドループ"],
  "GQ": [
    "Equatorial Guinea",
    "赤道几内亚",
    "赤道幾內亞",
    "Äquatorialguinea",
    "Guinée équatoriale",
    "赤道ギニア",
  ],
  "GR": ["Greece", "希腊", "希臘", "Griechenland", "Grèce", "ギリシャ"],
  "GS": [
    "South Georgia & South Sandwich Islands",
    "南乔治亚和南桑威奇群岛",
    "南喬治亞與南三明治群島",
    "Südgeorgien und die Südlichen Sandwichinseln",
    "Géorgie du Sud-et-les Îles Sandwich du Sud",
    "サウスジョージア・サウスサンドウィッチ諸島",
  ],
  "GT": ["Guatemala", "危地马拉", "瓜地馬拉", "Guatemala", "Guatemala", "グアテマラ"],
  "GU": ["Guam", "关岛", "關島", "Guam", "Guam", "グアム"],
  "GW": [
    "Guinea-Bissau",
    "几内亚比绍",
    "幾內亞比索",
    "Guinea-Bissau",
    "Guinée-Bissau",
    "ギニアビサウ",
  ],
  "GY": ["Guyana", "圭亚那", "蓋亞那", "Guyana", "Guyana", "ガイアナ"],
  "HK": [
    "Hong Kong SAR China",
    "中国香港特别行政区",
    "中國香港特別行政區",
    "Sonderverwaltungsregion Hongkong",
    "R.A.S. chinoise de Hong Kong",
    "中華人民共和国香港特別行政区",
  ],
  "HM": [
    "Heard & McDonald Islands",
    "赫德岛和麦克唐纳群岛",
    "赫德島及麥唐納群島",
    "Heard und McDonaldinseln",
    "Îles Heard-et-MacDonald",
    "ハード島・マクドナルド諸島",
  ],
  "HN": ["Honduras", "洪都拉斯", "宏都拉斯", "Honduras", "Honduras", "ホンジュラス"],
  "HR": ["Croatia", "克罗地亚", "克羅埃西亞", "Kroatien", "Croatie", "クロアチア"],
  "HT": ["Haiti", "海地", "海地", "Haiti", "Haïti", "ハイチ"],
  "HU": ["Hungary", "匈牙利", "匈牙利", "Ungarn", "Hongrie", "ハンガリー"],
  "IC": [
    "Canary Islands",
    "加纳利群岛",
    "加那利群島",
    "Kanarische Inseln",
    "Îles Canaries",
    "カナリア諸島",
  ],
  "ID": ["Indonesia", "印度尼西亚", "印尼", "Indonesien", "Indonésie", "インドネシア"],
  "IE": ["Ireland", "爱尔兰", "愛爾蘭", "Irland", "Irlande", "アイルランド"],
  "IL": ["Israel", "以色列", "以色列", "Israel", "Israël", "イスラエル"],
  "IM": ["Isle of Man", "马恩岛", "曼島", "Isle of Man", "Île de Man", "マン島"],
  "IN": ["India", "印度", "印度", "Indien", "Inde", "インド"],
  "IO": [
    "British Indian Ocean Territory",
    "英属印度洋领地",
    "英屬印度洋領地",
    "Britisches Territorium im Indischen Ozean",
    "Territoire britannique de l’océan Indien",
    "英領インド洋地域",
  ],
  "IQ": ["Iraq", "伊拉克", "伊拉克", "Irak", "Irak", "イラク"],
  "IR": ["Iran", "伊朗", "伊朗", "Iran", "Iran", "イラン"],
  "IS": ["Iceland", "冰岛", "冰島", "Island", "Islande", "アイスランド"],
  "IT": ["Italy", "意大利", "義大利", "Italien", "Italie", "イタリア"],
  "JE": ["Jersey", "泽西岛", "澤西島", "Jersey", "Jersey", "ジャージー"],
  "JM": ["Jamaica", "牙买加", "牙買加", "Jamaika", "Jamaïque", "ジャマイカ"],
  "JO": ["Jordan", "约旦", "約旦", "Jordanien", "Jordanie", "ヨルダン"],
  "JP": ["Japan", "日本", "日本", "Japan", "Japon", "日本"],
  "KE": ["Kenya", "肯尼亚", "肯亞", "Kenia", "Kenya", "ケニア"],
  "KG": ["Kyrgyzstan", "吉尔吉斯斯坦", "吉爾吉斯", "Kirgisistan", "Kirghizstan", "キルギス"],
  "KH": ["Cambodia", "柬埔寨", "柬埔寨", "Kambodscha", "Cambodge", "カンボジア"],
  "KI": ["Kiribati", "基里巴斯", "吉里巴斯", "Kiribati", "Kiribati", "キリバス"],
  "KM": ["Comoros", "科摩罗", "葛摩", "Komoren", "Comores", "コモロ"],
  "KN": [
    "St. Kitts & Nevis",
    "圣基茨和尼维斯",
    "聖克里斯多福及尼維斯",
    "St. Kitts und Nevis",
    "Saint-Christophe-et-Niévès",
    "セントクリストファー・ネーヴィス",
  ],
  "KP": ["North Korea", "朝鲜", "北韓", "Nordkorea", "Corée du Nord", "北朝鮮"],
  "KR": ["South Korea", "韩国", "南韓", "Südkorea", "Corée du Sud", "韓国"],
  "KW": ["Kuwait", "科威特", "科威特", "Kuwait", "Koweït", "クウェート"],
  "KY": [
    "Cayman Islands",
    "开曼群岛",
    "開曼群島",
    "Kaimaninseln",
    "Îles Caïmans",
    "ケイマン諸島",
  ],
  "KZ": ["Kazakhstan", "哈萨克斯坦", "哈薩克", "Kasachstan", "Kazakhstan", "カザフスタン"],
  "LA": ["Laos", "老挝", "寮國", "Laos", "Laos", "ラオス"],
  "LB": ["Lebanon", "黎巴嫩", "黎巴嫩", "Libanon", "Liban", "レバノン"],
  "LC": ["St. Lucia", "圣卢西亚", "聖露西亞", "St. Lucia", "Sainte-Lucie", "セントルシア"],
  "LI": [
    "Liechtenstein",
    "列支敦士登",
    "列支敦斯登",
    "Liechtenstein",
    "Liechtenstein",
    "リヒテンシュタイン",
  ],
  "LK": ["Sri Lanka", "斯里兰卡", "斯里蘭卡", "Sri Lanka", "Sri Lanka", "スリランカ"],
  "LR": ["Liberia", "利比里亚", "賴比瑞亞", "Liberia", "Liberia", "リベリア"],
  "LS": ["Lesotho", "莱索托", "賴索托", "Lesotho", "Lesotho", "レソト"],
  "LT": ["Lithuania", "立陶宛", "立陶宛", "Litauen", "Lituanie", "リトアニア"],
  "LU": ["Luxembourg", "卢森堡", "盧森堡", "Luxemburg", "Luxembourg", "ルクセンブルク"],
  "LV": ["Latvia", "拉脱维亚", "拉脫維亞", "Lettland", "Lettonie", "ラトビア"],
  "LY": ["Libya", "利比亚", "利比亞", "Libyen", "Libye", "リビア"],
  "MA": ["Morocco", "摩洛哥", "摩洛哥", "Marokko", "Maroc", "モロッコ"],
  "MC": ["Monaco", "摩纳哥", "摩納哥", "Monaco", "Monaco", "モナコ"],
  "MD": ["Moldova", "摩尔多瓦", "摩爾多瓦", "Republik Moldau", "Moldavie", "モルドバ"],
  "ME": ["Montenegro", "黑山", "蒙特內哥羅", "Montenegro", "Monténégro", "モンテネグロ"],
  "MF": [
    "St. Martin",
    "法属圣马丁",
    "法屬聖馬丁",
    "St. Martin",
    "Saint-Martin",
    "サン・マルタン",
  ],
  "MG": ["Madagascar", "马达加斯加", "馬達加斯加", "Madagaskar", "Madagascar", "マダガスカル"],
  "MH": [
    "Marshall Islands",
    "马绍尔群岛",
    "馬紹爾群島",
    "Marshallinseln",
    "Îles Marshall",
    "マーシャル諸島",
  ],
  "MK": [
    "North Macedonia",
    "北马其顿",
    "北馬其頓",
    "Nordmazedonien",
    "Macédoine du Nord",
    "北マケドニア",
  ],
  "ML": ["Mali", "马里", "馬利", "Mali", "Mali", "マリ"],
  "MM": [
    "Myanmar (Burma)",
    "缅甸",
    "緬甸",
    "Myanmar",
    "Myanmar (Birmanie)",
    "ミャンマー (ビルマ)",
  ],
  "MN": ["Mongolia", "蒙古", "蒙古", "Mongolei", "Mongolie", "モンゴル"],
  "MO": [
    "Macao SAR China",
    "中国澳门特别行政区",
    "中國澳門特別行政區",
    "Sonderverwaltungsregion Macau",
    "R.A.S. chinoise de Macao",
    "中華人民共和国マカオ特別行政区",
  ],
  "MP": [
    "Northern Mariana Islands",
    "北马里亚纳群岛",
    "北馬利安納群島",
    "Nördliche Marianen",
    "Îles Mariannes du Nord",
    "北マリアナ諸島",
  ],
  "MQ": ["Martinique", "马提尼克", "馬丁尼克", "Martinique", "Martinique", "マルティニーク"],
  "MR": ["Mauritania", "毛里塔尼亚", "茅利塔尼亞", "Mauretanien", "Mauritanie", "モーリタニア"],
  "MS": ["Montserrat", "蒙特塞拉特", "蒙哲臘", "Montserrat", "Montserrat", "モントセラト"],
  "MT": ["Malta", "马耳他", "馬爾他", "Malta", "Malte", "マルタ"],
  "MU": ["Mauritius", "毛里求斯", "模里西斯", "Mauritius", "Maurice", "モーリシャス"],
  "MV": ["Maldives", "马尔代夫", "馬爾地夫", "Malediven", "Maldives", "モルディブ"],
  "MW": ["Malawi", "马拉维", "馬拉威", "Malawi", "Malawi", "マラウイ"],
  "MX": ["Mexico", "墨西哥", "墨西哥", "Mexiko", "Mexique", "メキシコ"],
  "MY": ["Malaysia", "马来西亚", "馬來西亞", "Malaysia", "Malaisie", "マレーシア"],
  "MZ": ["Mozambique", "莫桑比克", "莫三比克", "Mosambik", "Mozambique", "モザンビーク"],
  "NA": ["Namibia", "纳米比亚", "納米比亞", "Namibia", "Namibie", "ナミビア"],
  "NC": [
    "New Caledonia",
    "新喀里多尼亚",
    "新喀里多尼亞",
    "Neukaledonien",
    "Nouvelle-Calédonie",
    "ニューカレドニア",
  ],
  "NE": ["Niger", "尼日尔", "尼日", "Niger", "Niger", "ニジェール"],
  "NF": [
    "Norfolk Island",
    "诺福克岛",
    "諾福克島",
    "Norfolkinsel",
    "Île Norfolk",
    "ノーフォーク島",
  ],
  "NG": ["Nigeria", "尼日利亚", "奈及利亞", "Nigeria", "Nigeria", "ナイジェリア"],
  "NI": ["Nicaragua", "尼加拉瓜", "尼加拉瓜", "Nicaragua", "Nicaragua", "ニカラグア"],
  "NL": ["Netherlands", "荷兰", "荷蘭", "Niederlande", "Pays-Bas", "オランダ"],
  "NO": ["Norway", "挪威", "挪威", "Norwegen", "Norvège", "ノルウェー"],
  "NP": ["Nepal", "尼泊尔", "尼泊爾", "Nepal", "Népal", "ネパール"],
  "NR": ["Nauru", "瑙鲁", "諾魯", "Nauru", "Nauru", "ナウル"],
  "NU": ["Niue", "纽埃", "紐埃島", "Niue", "Niue", "ニウエ"],
  "NZ": [
    "New Zealand",
    "新西兰",
    "紐西蘭",
    "Neuseeland",
    "Nouvelle-Zélande",
    "ニュージーランド",
  ],
  "OM": ["Oman", "阿曼", "阿曼", "Oman", "Oman", "オマーン"],
  "PA": ["Panama", "巴拿马", "巴拿馬", "Panama", "Panama", "パナマ"],
  "PE": ["Peru", "秘鲁", "秘魯", "Peru", "Pérou", "ペルー"],
  "PF": [
    "French Polynesia",
    "法属波利尼西亚",
    "法屬玻里尼西亞",
    "Französisch-Polynesien",
    "Polynésie française",
    "仏領ポリネシア",
  ],
  "PG": [
    "Papua New Guinea",
    "巴布亚新几内亚",
    "巴布亞紐幾內亞",
    "Papua-Neuguinea",
    "Papouasie-Nouvelle-Guinée",
    "パプアニューギニア",
  ],
  "PH": ["Philippines", "菲律宾", "菲律賓", "Philippinen", "Philippines", "フィリピン"],
  "PK": ["Pakistan", "巴基斯坦", "巴基斯坦", "Pakistan", "Pakistan", "パキスタン"],
  "PL": ["Poland", "波兰", "波蘭", "Polen", "Pologne", "ポーランド"],
  "PM": [
    "St. Pierre & Miquelon",
    "圣皮埃尔和密克隆群岛",
    "聖皮埃與密克隆群島",
    "St. Pierre und Miquelon",
    "Saint-Pierre-et-Miquelon",
    "サンピエール島・ミクロン島",
  ],
  "PN": [
    "Pitcairn Islands",
    "皮特凯恩群岛",
    "皮特肯群島",
    "Pitcairninseln",
    "Îles Pitcairn",
    "ピトケアン諸島",
  ],
  "PR": ["Puerto Rico", "波多黎各", "波多黎各", "Puerto Rico", "Porto Rico", "プエルトリコ"],
  "PS": [
    "Palestinian Territories",
    "巴勒斯坦领土",
    "巴勒斯坦自治區",
    "Palästinensische Autonomiegebiete",
    "Territoires palestiniens",
    "パレスチナ自治区",
  ],
  "PT": ["Portugal", "葡萄牙", "葡萄牙", "Portugal", "Portugal", "ポルトガル"],
  "PW": ["Palau", "帕劳", "帛琉", "Palau", "Palaos", "パラオ"],
  "PY": ["Paraguay", "巴拉圭", "巴拉圭", "Paraguay", "Paraguay", "パラグアイ"],
  "QA": ["Qatar", "卡塔尔", "卡達", "Katar", "Qatar", "カタール"],
  "QO": [
    "Outlying Oceania",
    "大洋洲边远群岛",
    "大洋洲邊疆群島",
    "Äußeres Ozeanien",
    "régions éloignées de l’Océanie",
    "オセアニア周辺地域",
  ],
  "RE": ["Réunion", "留尼汪", "留尼旺", "Réunion", "La Réunion", "レユニオン"],
  "RO": ["Romania", "罗马尼亚", "羅馬尼亞", "Rumänien", "Roumanie", "ルーマニア"],
  "RS": ["Serbia", "塞尔维亚", "塞爾維亞", "Serbien", "Serbie", "セルビア"],
  "RU": ["Russia", "俄罗斯", "俄羅斯", "Russland", "Russie", "ロシア"],
  "RW": ["Rwanda", "卢旺达", "盧安達", "Ruanda", "Rwanda", "ルワンダ"],
  "SA": [
    "Saudi Arabia",
    "沙特阿拉伯",
    "沙烏地阿拉伯",
    "Saudi-Arabien",
    "Arabie saoudite",
    "サウジアラビア",
  ],
  "SB": [
    "Solomon Islands",
    "所罗门群岛",
    "索羅門群島",
    "Salomonen",
    "Îles Salomon",
    "ソロモン諸島",
  ],
  "SC": ["Seychelles", "塞舌尔", "塞席爾", "Seychellen", "Seychelles", "セーシェル"],
  "SD": ["Sudan", "苏丹", "蘇丹", "Sudan", "Soudan", "スーダン"],
  "SE": ["Sweden", "瑞典", "瑞典", "Schweden", "Suède", "スウェーデン"],
  "SG": ["Singapore", "新加坡", "新加坡", "Singapur", "Singapour", "シンガポール"],
  "SH": [
    "St. Helena",
    "圣赫勒拿",
    "聖赫勒拿島",
    "St. Helena",
    "Sainte-Hélène",
    "セントヘレナ",
  ],
  "SI": ["Slovenia", "斯洛文尼亚", "斯洛維尼亞", "Slowenien", "Slovénie", "スロベニア"],
  "SJ": [
    "Svalbard & Jan Mayen",
    "斯瓦尔巴和扬马延",
    "挪威屬斯瓦巴及尖棉",
    "Spitzbergen und Jan Mayen",
    "Svalbard et Jan Mayen",
    "スバールバル諸島・ヤンマイエン島",
  ],
  "SK": ["Slovakia", "斯洛伐克", "斯洛伐克", "Slowakei", "Slovaquie", "スロバキア"],
  "SL": [
    "Sierra Leone",
    "塞拉利昂",
    "獅子山",
    "Sierra Leone",
    "Sierra Leone",
    "シエラレオネ",
  ],
  "SM": ["San Marino", "圣马力诺", "聖馬利諾", "San Marino", "Saint-Marin", "サンマリノ"],
  "SN": ["Senegal", "塞内加尔", "塞內加爾", "Senegal", "Sénégal", "セネガル"],
  "SO": ["Somalia", "索马里", "索馬利亞", "Somalia", "Somalie", "ソマリア"],
  "SR": ["Suriname", "苏里南", "蘇利南", "Suriname", "Suriname", "スリナム"],
  "SS": ["South Sudan", "南苏丹", "南蘇丹", "Südsudan", "Soudan du Sud", "南スーダン"],
  "ST": [
    "São Tomé & Príncipe",
    "圣多美和普林西比",
    "聖多美普林西比",
    "São Tomé und Príncipe",
    "Sao Tomé-et-Principe",
    "サントメ・プリンシペ",
  ],
  "SV": ["El Salvador", "萨尔瓦多", "薩爾瓦多", "El Salvador", "Salvador", "エルサルバドル"],
  "SX": [
    "Sint Maarten",
    "荷属圣马丁",
    "荷屬聖馬丁",
    "Sint Maarten",
    "Saint-Martin (partie néerlandaise)",
    "シント・マールテン",
  ],
  "SY": ["Syria", "叙利亚", "敘利亞", "Syrien", "Syrie", "シリア"],
  "SZ": ["Eswatini", "斯威士兰", "史瓦帝尼", "Eswatini", "Eswatini", "エスワティニ"],
  "TA": [
    "Tristan da Cunha",
    "特里斯坦-达库尼亚群岛",
    "特里斯坦達庫尼亞群島",
    "Tristan da Cunha",
    "Tristan da Cunha",
    "トリスタン・ダ・クーニャ",
  ],
  "TC": [
    "Turks & Caicos Islands",
    "特克斯和凯科斯群岛",
    "土克斯及開科斯群島",
    "Turks- und Caicosinseln",
    "Îles Turques-et-Caïques",
    "タークス・カイコス諸島",
  ],
  "TD": ["Chad", "乍得", "查德", "Tschad", "Tchad", "チャド"],
  "TF": [
    "French Southern Territories",
    "法属南部领地",
    "法屬南部屬地",
    "Französische Süd- und Antarktisgebiete",
    "Terres australes françaises",
    "仏領極南諸島",
  ],
  "TG": ["Togo", "多哥", "多哥", "Togo", "Togo", "トーゴ"],
  "TH": ["Thailand", "泰国", "泰國", "Thailand", "Thaïlande", "タイ"],
  "TJ": [
    "Tajikistan",
    "塔吉克斯坦",
    "塔吉克",
    "Tadschikistan",
    "Tadjikistan",
    "タジキスタン",
  ],
  "TK": ["Tokelau", "托克劳", "托克勞群島", "Tokelau", "Tokelau", "トケラウ"],
  "TL": [
    "Timor-Leste",
    "东帝汶",
    "東帝汶",
    "Timor-Leste",
    "Timor oriental",
    "東ティモール",
  ],
  "TM": [
    "Turkmenistan",
    "土库曼斯坦",
    "土庫曼",
    "Turkmenistan",
    "Turkménistan",
    "トルクメニスタン",
  ],
  "TN": ["Tunisia", "突尼斯", "突尼西亞", "Tunesien", "Tunisie", "チュニジア"],
  "TO": ["Tonga", "汤加", "東加", "Tonga", "Tonga", "トンガ"],
  "TR": ["Türkiye", "土耳其", "土耳其", "Türkei", "Turquie", "トルコ"],
  "TT": [
    "Trinidad & Tobago",
    "特立尼达和多巴哥",
    "千里達及托巴哥",
    "Trinidad und Tobago",
    "Trinité-et-Tobago",
    "トリニダード・トバゴ",
  ],
  "TV": ["Tuvalu", "图瓦卢", "吐瓦魯", "Tuvalu", "Tuvalu", "ツバル"],
  "TW": ["Taiwan", "台湾", "台灣", "Taiwan", "Taïwan", "台湾"],
  "TZ": ["Tanzania", "坦桑尼亚", "坦尚尼亞", "Tansania", "Tanzanie", "タンザニア"],
  "UA": ["Ukraine", "乌克兰", "烏克蘭", "Ukraine", "Ukraine", "ウクライナ"],
  "UG": ["Uganda", "乌干达", "烏干達", "Uganda", "Ouganda", "ウガンダ"],
  "UM": [
    "U.S. Outlying Islands",
    "美国本土外小岛屿",
    "美國本土外小島嶼",
    "Amerikanische Überseeinseln",
    "Îles mineures éloignées des États-Unis",
    "合衆国領有小離島",
  ],
  "UN": [
    "United Nations",
    "联合国",
    "聯合國",
    "Vereinte Nationen",
    "Nations Unies",
    "国際連合",
  ],
  "US": [
    "United States",
    "美国",
    "美國",
    "Vereinigte Staaten",
    "États-Unis",
    "アメリカ合衆国",
  ],
  "UY": ["Uruguay", "乌拉圭", "烏拉圭", "Uruguay", "Uruguay", "ウルグアイ"],
  "UZ": [
    "Uzbekistan",
    "乌兹别克斯坦",
    "烏茲別克",
    "Usbekistan",
    "Ouzbékistan",
    "ウズベキスタン",
  ],
  "VA": [
    "Vatican City",
    "梵蒂冈",
    "梵蒂岡",
    "Vatikanstadt",
    "État de la Cité du Vatican",
    "バチカン市国",
  ],
  "VC": [
    "St. Vincent & Grenadines",
    "圣文森特和格林纳丁斯",
    "聖文森及格瑞那丁",
    "St. Vincent und die Grenadinen",
    "Saint-Vincent-et-les Grenadines",
    "セントビンセント及びグレナディーン諸島",
  ],
  "VE": ["Venezuela", "委内瑞拉", "委內瑞拉", "Venezuela", "Venezuela", "ベネズエラ"],
  "VG": [
    "British Virgin Islands",
    "英属维尔京群岛",
    "英屬維京群島",
    "Britische Jungferninseln",
    "Îles Vierges britanniques",
    "英領ヴァージン諸島",
  ],
  "VI": [
    "U.S. Virgin Islands",
    "美属维尔京群岛",
    "美屬維京群島",
    "Amerikanische Jungferninseln",
    "Îles Vierges des États-Unis",
    "米領ヴァージン諸島",
  ],
  "VN": ["Vietnam", "越南", "越南", "Vietnam", "Viêt Nam", "ベトナム"],
  "VU": ["Vanuatu", "瓦努阿图", "萬那杜", "Vanuatu", "Vanuatu", "バヌアツ"],
  "WF": [
    "Wallis & Futuna",
    "瓦利斯和富图纳",
    "瓦利斯群島和富圖那群島",
    "Wallis und Futuna",
    "Wallis-et-Futuna",
    "ウォリス・フツナ",
  ],
  "WS": ["Samoa", "萨摩亚", "薩摩亞", "Samoa", "Samoa", "サモア"],
  "XA": [
    "Pseudo-Accents",
    "伪地区",
    "偽區域",
    "Pseudo-Akzente",
    "pseudo-accents",
    "疑似アクセント",
  ],
  "XB": [
    "Pseudo-Bidi",
    "伪双向语言地区",
    "偽比迪",
    "Pseudo-Bidi",
    "pseudo-bidi",
    "疑似 BIDI",
  ],
  "XK": ["Kosovo", "科索沃", "科索沃", "Kosovo", "Kosovo", "コソボ"],
  "YE": ["Yemen", "也门", "葉門", "Jemen", "Yémen", "イエメン"],
  "YT": ["Mayotte", "马约特", "馬約特島", "Mayotte", "Mayotte", "マヨット"],
  "ZA": ["South Africa", "南非", "南非", "Südafrika", "Afrique du Sud", "南アフリカ"],
  "ZM": ["Zambia", "赞比亚", "尚比亞", "Sambia", "Zambie", "ザンビア"],
  "ZW": ["Zimbabwe", "津巴布韦", "辛巴威", "Simbabwe", "Zimbabwe", "ジンバブエ"],
  "ZZ": [
    "Unknown Region",
    "未知地区",
    "未知區域",
    "Unbekannte Region",
    "région inconnue",
    "不明な地域",
  ],
};
