import 'package:flutter/widgets.dart';

import '../../l10n/app_localizations.dart';

/// 内置工具显示当前语言名称，外部工具与自定义名称保留原始标识。
String openHandToolDisplayName(BuildContext context, String name) {
  final l10n = AppLocalizations.of(context)!;
  return switch (name.trim().toLowerCase()) {
    'task' => l10n.messageToolNameTask,
    'bash' => l10n.messageToolNameBash,
    'bashbackground' => l10n.messageToolNameBashBackground,
    'taskoutput' => l10n.messageToolNameTaskOutput,
    'taskstop' => l10n.messageToolNameTaskStop,
    'glob' => l10n.messageToolNameGlob,
    'grep' => l10n.messageToolNameGrep,
    'ls' => l10n.messageToolNameLs,
    'exitplanmode' => l10n.messageToolNameExitPlanMode,
    'endvoiceconversation' => l10n.messageToolNameEndVoiceConversation,
    'read' => l10n.messageToolNameRead,
    'edit' => l10n.messageToolNameEdit,
    'multiedit' => l10n.messageToolNameMultiEdit,
    'applyfilediffs' => l10n.messageToolNameApplyFileDiffs,
    'write' => l10n.messageToolNameWrite,
    'notebookedit' => l10n.messageToolNameNotebookEdit,
    'webfetch' => l10n.messageToolNameWebFetch,
    'todowrite' => l10n.messageToolNameTodoWrite,
    'websearch' => l10n.messageToolNameWebSearch,
    'lsp' => l10n.messageToolNameLsp,
    'codebasesearch' => l10n.messageToolNameCodebaseSearch,
    'git' => l10n.messageToolNameGit,
    'deletefile' => l10n.messageToolNameDeleteFile,
    'readlints' => l10n.messageToolNameReadLints,
    'askuserchoice' => l10n.messageToolNameAskUserChoice,
    'skillmanager' => l10n.messageToolNameSkillManager,
    'toolsearch' => l10n.messageToolNameToolSearch,
    'memory' => l10n.messageToolNameMemory,
    'knowledgesearch' => l10n.messageToolNameKnowledgeSearch,
    'knowledgeread' => l10n.messageToolNameKnowledgeRead,
    'workflowlist' => l10n.messageToolNameWorkflowList,
    'workflowdetail' => l10n.messageToolNameWorkflowDetail,
    'workflowexecute' => l10n.messageToolNameWorkflowExecute,
    'workflowexecutionstatus' => l10n.messageToolNameWorkflowExecutionStatus,
    'croncreate' => l10n.messageToolNameCronCreate,
    'cronedit' => l10n.messageToolNameCronEdit,
    'crondelete' => l10n.messageToolNameCronDelete,
    'cronenable' => l10n.messageToolNameCronEnable,
    'crondisable' => l10n.messageToolNameCronDisable,
    'machineterminalread' => l10n.messageToolNameMachineTerminalRead,
    'machineterminalwrite' => l10n.messageToolNameMachineTerminalWrite,
    'machineterminalexec' => l10n.messageToolNameMachineTerminalExec,
    'machineterminalcontrol' => l10n.messageToolNameMachineTerminalControl,
    'dingtalktoolsearch' => l10n.messageToolNameDingTalkToolSearch,
    'dingtalkdws' => l10n.messageToolNameDingtalkDws,
    'dingtalkimagegeneration' => l10n.messageToolNameDingtalkImageGeneration,
    'dingtalkvideogeneration' => l10n.messageToolNameDingtalkVideoGeneration,
    'dingtalkaudiogeneration' => l10n.messageToolNameDingtalkAudioGeneration,
    'downloadfile' => l10n.messageToolNameDownloadFile,
    'terminalread' => l10n.messageToolNameMachineTerminalRead,
    'terminalwrite' => l10n.messageToolNameMachineTerminalWrite,
    'terminalexec' => l10n.messageToolNameMachineTerminalExec,
    'terminalcontrol' => l10n.messageToolNameMachineTerminalControl,
    _ => name,
  };
}
